// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_tanh_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_tanh_config3_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        p_read,
        p_read1,
        p_read2,
        p_read3,
        p_read4,
        p_read5,
        p_read6,
        p_read7,
        p_read8,
        p_read9,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [15:0] p_read;
input  [15:0] p_read1;
input  [15:0] p_read2;
input  [15:0] p_read3;
input  [15:0] p_read4;
input  [15:0] p_read5;
input  [15:0] p_read6;
input  [15:0] p_read7;
input  [15:0] p_read8;
input  [15:0] p_read9;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;

reg ap_done;
reg ap_idle;
reg ap_ready;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_pp0_stage0_11001;
wire   [9:0] tanh_table_address0;
reg    tanh_table_ce0;
wire   [10:0] tanh_table_q0;
wire   [9:0] tanh_table_address1;
reg    tanh_table_ce1;
wire   [10:0] tanh_table_q1;
wire   [9:0] tanh_table_address2;
reg    tanh_table_ce2;
wire   [10:0] tanh_table_q2;
wire   [9:0] tanh_table_address3;
reg    tanh_table_ce3;
wire   [10:0] tanh_table_q3;
wire   [9:0] tanh_table_address4;
reg    tanh_table_ce4;
wire   [10:0] tanh_table_q4;
wire   [9:0] tanh_table_address5;
reg    tanh_table_ce5;
wire   [10:0] tanh_table_q5;
wire   [9:0] tanh_table_address6;
reg    tanh_table_ce6;
wire   [10:0] tanh_table_q6;
wire   [9:0] tanh_table_address7;
reg    tanh_table_ce7;
wire   [10:0] tanh_table_q7;
wire   [9:0] tanh_table_address8;
reg    tanh_table_ce8;
wire   [10:0] tanh_table_q8;
wire   [9:0] tanh_table_address9;
reg    tanh_table_ce9;
wire   [10:0] tanh_table_q9;
wire   [9:0] select_ln438_fu_375_p3;
reg   [9:0] select_ln438_reg_1675;
wire   [9:0] select_ln438_1_fu_503_p3;
reg   [9:0] select_ln438_1_reg_1680;
wire   [9:0] select_ln438_2_fu_631_p3;
reg   [9:0] select_ln438_2_reg_1685;
wire   [9:0] select_ln438_3_fu_759_p3;
reg   [9:0] select_ln438_3_reg_1690;
wire   [9:0] select_ln438_4_fu_887_p3;
reg   [9:0] select_ln438_4_reg_1695;
wire   [9:0] select_ln438_5_fu_1015_p3;
reg   [9:0] select_ln438_5_reg_1700;
wire   [9:0] select_ln438_6_fu_1143_p3;
reg   [9:0] select_ln438_6_reg_1705;
wire   [9:0] select_ln438_7_fu_1271_p3;
reg   [9:0] select_ln438_7_reg_1710;
wire   [9:0] select_ln438_8_fu_1399_p3;
reg   [9:0] select_ln438_8_reg_1715;
wire   [9:0] select_ln438_9_fu_1527_p3;
reg   [9:0] select_ln438_9_reg_1720;
wire    ap_block_pp0_stage0_subdone;
wire   [63:0] zext_ln440_fu_1535_p1;
wire   [63:0] zext_ln440_1_fu_1539_p1;
wire   [63:0] zext_ln440_2_fu_1543_p1;
wire   [63:0] zext_ln440_3_fu_1547_p1;
wire   [63:0] zext_ln440_4_fu_1551_p1;
wire   [63:0] zext_ln440_5_fu_1555_p1;
wire   [63:0] zext_ln440_6_fu_1559_p1;
wire   [63:0] zext_ln440_7_fu_1563_p1;
wire   [63:0] zext_ln440_8_fu_1567_p1;
wire   [63:0] zext_ln440_9_fu_1571_p1;
wire   [12:0] tmp_fu_263_p4;
wire   [25:0] shl_ln_fu_255_p3;
wire   [2:0] trunc_ln851_fu_283_p1;
wire   [9:0] p_Result_2_fu_287_p3;
wire  signed [13:0] sext_ln850_fu_273_p1;
wire   [0:0] icmp_ln851_fu_295_p2;
wire   [13:0] add_ln691_fu_301_p2;
wire   [0:0] icmp_ln850_fu_277_p2;
wire   [13:0] select_ln850_fu_307_p3;
wire   [13:0] select_ln545_fu_315_p3;
wire   [12:0] trunc_ln434_fu_323_p1;
wire   [13:0] add_ln434_fu_327_p2;
wire   [0:0] tmp_1_fu_339_p3;
wire   [12:0] add_ln436_fu_333_p2;
wire   [12:0] select_ln436_fu_347_p3;
wire   [2:0] tmp_3_fu_359_p4;
wire   [0:0] icmp_ln438_fu_369_p2;
wire   [9:0] trunc_ln438_fu_355_p1;
wire   [12:0] tmp_2_fu_391_p4;
wire   [25:0] shl_ln1118_1_fu_383_p3;
wire   [2:0] trunc_ln851_1_fu_411_p1;
wire   [9:0] p_Result_2_1_fu_415_p3;
wire  signed [13:0] sext_ln850_1_fu_401_p1;
wire   [0:0] icmp_ln851_1_fu_423_p2;
wire   [13:0] add_ln691_1_fu_429_p2;
wire   [0:0] icmp_ln850_1_fu_405_p2;
wire   [13:0] select_ln850_1_fu_435_p3;
wire   [13:0] select_ln545_1_fu_443_p3;
wire   [12:0] trunc_ln434_1_fu_451_p1;
wire   [13:0] add_ln434_1_fu_455_p2;
wire   [0:0] tmp_5_fu_467_p3;
wire   [12:0] add_ln436_1_fu_461_p2;
wire   [12:0] select_ln436_1_fu_475_p3;
wire   [2:0] tmp_7_fu_487_p4;
wire   [0:0] icmp_ln438_1_fu_497_p2;
wire   [9:0] trunc_ln438_1_fu_483_p1;
wire   [12:0] tmp_4_fu_519_p4;
wire   [25:0] shl_ln1118_2_fu_511_p3;
wire   [2:0] trunc_ln851_2_fu_539_p1;
wire   [9:0] p_Result_2_2_fu_543_p3;
wire  signed [13:0] sext_ln850_2_fu_529_p1;
wire   [0:0] icmp_ln851_2_fu_551_p2;
wire   [13:0] add_ln691_2_fu_557_p2;
wire   [0:0] icmp_ln850_2_fu_533_p2;
wire   [13:0] select_ln850_2_fu_563_p3;
wire   [13:0] select_ln545_2_fu_571_p3;
wire   [12:0] trunc_ln434_2_fu_579_p1;
wire   [13:0] add_ln434_2_fu_583_p2;
wire   [0:0] tmp_9_fu_595_p3;
wire   [12:0] add_ln436_2_fu_589_p2;
wire   [12:0] select_ln436_2_fu_603_p3;
wire   [2:0] tmp_10_fu_615_p4;
wire   [0:0] icmp_ln438_2_fu_625_p2;
wire   [9:0] trunc_ln438_2_fu_611_p1;
wire   [12:0] tmp_6_fu_647_p4;
wire   [25:0] shl_ln1118_3_fu_639_p3;
wire   [2:0] trunc_ln851_3_fu_667_p1;
wire   [9:0] p_Result_2_3_fu_671_p3;
wire  signed [13:0] sext_ln850_3_fu_657_p1;
wire   [0:0] icmp_ln851_3_fu_679_p2;
wire   [13:0] add_ln691_3_fu_685_p2;
wire   [0:0] icmp_ln850_3_fu_661_p2;
wire   [13:0] select_ln850_3_fu_691_p3;
wire   [13:0] select_ln545_3_fu_699_p3;
wire   [12:0] trunc_ln434_3_fu_707_p1;
wire   [13:0] add_ln434_3_fu_711_p2;
wire   [0:0] tmp_12_fu_723_p3;
wire   [12:0] add_ln436_3_fu_717_p2;
wire   [12:0] select_ln436_3_fu_731_p3;
wire   [2:0] tmp_14_fu_743_p4;
wire   [0:0] icmp_ln438_3_fu_753_p2;
wire   [9:0] trunc_ln438_3_fu_739_p1;
wire   [12:0] tmp_8_fu_775_p4;
wire   [25:0] shl_ln1118_4_fu_767_p3;
wire   [2:0] trunc_ln851_4_fu_795_p1;
wire   [9:0] p_Result_2_4_fu_799_p3;
wire  signed [13:0] sext_ln850_4_fu_785_p1;
wire   [0:0] icmp_ln851_4_fu_807_p2;
wire   [13:0] add_ln691_4_fu_813_p2;
wire   [0:0] icmp_ln850_4_fu_789_p2;
wire   [13:0] select_ln850_4_fu_819_p3;
wire   [13:0] select_ln545_4_fu_827_p3;
wire   [12:0] trunc_ln434_4_fu_835_p1;
wire   [13:0] add_ln434_4_fu_839_p2;
wire   [0:0] tmp_16_fu_851_p3;
wire   [12:0] add_ln436_4_fu_845_p2;
wire   [12:0] select_ln436_4_fu_859_p3;
wire   [2:0] tmp_18_fu_871_p4;
wire   [0:0] icmp_ln438_4_fu_881_p2;
wire   [9:0] trunc_ln438_4_fu_867_p1;
wire   [12:0] tmp_s_fu_903_p4;
wire   [25:0] shl_ln1118_5_fu_895_p3;
wire   [2:0] trunc_ln851_5_fu_923_p1;
wire   [9:0] p_Result_2_5_fu_927_p3;
wire  signed [13:0] sext_ln850_5_fu_913_p1;
wire   [0:0] icmp_ln851_5_fu_935_p2;
wire   [13:0] add_ln691_5_fu_941_p2;
wire   [0:0] icmp_ln850_5_fu_917_p2;
wire   [13:0] select_ln850_5_fu_947_p3;
wire   [13:0] select_ln545_5_fu_955_p3;
wire   [12:0] trunc_ln434_5_fu_963_p1;
wire   [13:0] add_ln434_5_fu_967_p2;
wire   [0:0] tmp_19_fu_979_p3;
wire   [12:0] add_ln436_5_fu_973_p2;
wire   [12:0] select_ln436_5_fu_987_p3;
wire   [2:0] tmp_20_fu_999_p4;
wire   [0:0] icmp_ln438_5_fu_1009_p2;
wire   [9:0] trunc_ln438_5_fu_995_p1;
wire   [12:0] tmp_11_fu_1031_p4;
wire   [25:0] shl_ln1118_6_fu_1023_p3;
wire   [2:0] trunc_ln851_6_fu_1051_p1;
wire   [9:0] p_Result_2_6_fu_1055_p3;
wire  signed [13:0] sext_ln850_6_fu_1041_p1;
wire   [0:0] icmp_ln851_6_fu_1063_p2;
wire   [13:0] add_ln691_6_fu_1069_p2;
wire   [0:0] icmp_ln850_6_fu_1045_p2;
wire   [13:0] select_ln850_6_fu_1075_p3;
wire   [13:0] select_ln545_6_fu_1083_p3;
wire   [12:0] trunc_ln434_6_fu_1091_p1;
wire   [13:0] add_ln434_6_fu_1095_p2;
wire   [0:0] tmp_21_fu_1107_p3;
wire   [12:0] add_ln436_6_fu_1101_p2;
wire   [12:0] select_ln436_6_fu_1115_p3;
wire   [2:0] tmp_22_fu_1127_p4;
wire   [0:0] icmp_ln438_6_fu_1137_p2;
wire   [9:0] trunc_ln438_6_fu_1123_p1;
wire   [12:0] tmp_13_fu_1159_p4;
wire   [25:0] shl_ln1118_7_fu_1151_p3;
wire   [2:0] trunc_ln851_7_fu_1179_p1;
wire   [9:0] p_Result_2_7_fu_1183_p3;
wire  signed [13:0] sext_ln850_7_fu_1169_p1;
wire   [0:0] icmp_ln851_7_fu_1191_p2;
wire   [13:0] add_ln691_7_fu_1197_p2;
wire   [0:0] icmp_ln850_7_fu_1173_p2;
wire   [13:0] select_ln850_7_fu_1203_p3;
wire   [13:0] select_ln545_7_fu_1211_p3;
wire   [12:0] trunc_ln434_7_fu_1219_p1;
wire   [13:0] add_ln434_7_fu_1223_p2;
wire   [0:0] tmp_23_fu_1235_p3;
wire   [12:0] add_ln436_7_fu_1229_p2;
wire   [12:0] select_ln436_7_fu_1243_p3;
wire   [2:0] tmp_24_fu_1255_p4;
wire   [0:0] icmp_ln438_7_fu_1265_p2;
wire   [9:0] trunc_ln438_7_fu_1251_p1;
wire   [12:0] tmp_15_fu_1287_p4;
wire   [25:0] shl_ln1118_8_fu_1279_p3;
wire   [2:0] trunc_ln851_8_fu_1307_p1;
wire   [9:0] p_Result_2_8_fu_1311_p3;
wire  signed [13:0] sext_ln850_8_fu_1297_p1;
wire   [0:0] icmp_ln851_8_fu_1319_p2;
wire   [13:0] add_ln691_8_fu_1325_p2;
wire   [0:0] icmp_ln850_8_fu_1301_p2;
wire   [13:0] select_ln850_8_fu_1331_p3;
wire   [13:0] select_ln545_8_fu_1339_p3;
wire   [12:0] trunc_ln434_8_fu_1347_p1;
wire   [13:0] add_ln434_8_fu_1351_p2;
wire   [0:0] tmp_25_fu_1363_p3;
wire   [12:0] add_ln436_8_fu_1357_p2;
wire   [12:0] select_ln436_8_fu_1371_p3;
wire   [2:0] tmp_26_fu_1383_p4;
wire   [0:0] icmp_ln438_8_fu_1393_p2;
wire   [9:0] trunc_ln438_8_fu_1379_p1;
wire   [12:0] tmp_17_fu_1415_p4;
wire   [25:0] shl_ln1118_9_fu_1407_p3;
wire   [2:0] trunc_ln851_9_fu_1435_p1;
wire   [9:0] p_Result_2_9_fu_1439_p3;
wire  signed [13:0] sext_ln850_9_fu_1425_p1;
wire   [0:0] icmp_ln851_9_fu_1447_p2;
wire   [13:0] add_ln691_9_fu_1453_p2;
wire   [0:0] icmp_ln850_9_fu_1429_p2;
wire   [13:0] select_ln850_9_fu_1459_p3;
wire   [13:0] select_ln545_9_fu_1467_p3;
wire   [12:0] trunc_ln434_9_fu_1475_p1;
wire   [13:0] add_ln434_9_fu_1479_p2;
wire   [0:0] tmp_27_fu_1491_p3;
wire   [12:0] add_ln436_9_fu_1485_p2;
wire   [12:0] select_ln436_9_fu_1499_p3;
wire   [2:0] tmp_28_fu_1511_p4;
wire   [0:0] icmp_ln438_9_fu_1521_p2;
wire   [9:0] trunc_ln438_9_fu_1507_p1;
wire  signed [15:0] sext_ln703_fu_1575_p1;
wire  signed [15:0] sext_ln703_1_fu_1579_p1;
wire  signed [15:0] sext_ln703_2_fu_1583_p1;
wire  signed [15:0] sext_ln703_3_fu_1587_p1;
wire  signed [15:0] sext_ln703_4_fu_1591_p1;
wire  signed [15:0] sext_ln703_5_fu_1595_p1;
wire  signed [15:0] sext_ln703_6_fu_1599_p1;
wire  signed [15:0] sext_ln703_7_fu_1603_p1;
wire  signed [15:0] sext_ln703_8_fu_1607_p1;
wire  signed [15:0] sext_ln703_9_fu_1611_p1;
reg   [0:0] ap_NS_fsm;
reg    ap_idle_pp0_0to1;
reg    ap_reset_idle_pp0;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
end

myproject_tanh_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_tanh_config3_s_tanh_table #(
    .DataWidth( 11 ),
    .AddressRange( 1024 ),
    .AddressWidth( 10 ))
tanh_table_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(tanh_table_address0),
    .ce0(tanh_table_ce0),
    .q0(tanh_table_q0),
    .address1(tanh_table_address1),
    .ce1(tanh_table_ce1),
    .q1(tanh_table_q1),
    .address2(tanh_table_address2),
    .ce2(tanh_table_ce2),
    .q2(tanh_table_q2),
    .address3(tanh_table_address3),
    .ce3(tanh_table_ce3),
    .q3(tanh_table_q3),
    .address4(tanh_table_address4),
    .ce4(tanh_table_ce4),
    .q4(tanh_table_q4),
    .address5(tanh_table_address5),
    .ce5(tanh_table_ce5),
    .q5(tanh_table_q5),
    .address6(tanh_table_address6),
    .ce6(tanh_table_ce6),
    .q6(tanh_table_q6),
    .address7(tanh_table_address7),
    .ce7(tanh_table_ce7),
    .q7(tanh_table_q7),
    .address8(tanh_table_address8),
    .ce8(tanh_table_ce8),
    .q8(tanh_table_q8),
    .address9(tanh_table_address9),
    .ce9(tanh_table_ce9),
    .q9(tanh_table_q9)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        select_ln438_1_reg_1680 <= select_ln438_1_fu_503_p3;
        select_ln438_2_reg_1685 <= select_ln438_2_fu_631_p3;
        select_ln438_3_reg_1690 <= select_ln438_3_fu_759_p3;
        select_ln438_4_reg_1695 <= select_ln438_4_fu_887_p3;
        select_ln438_5_reg_1700 <= select_ln438_5_fu_1015_p3;
        select_ln438_6_reg_1705 <= select_ln438_6_fu_1143_p3;
        select_ln438_7_reg_1710 <= select_ln438_7_fu_1271_p3;
        select_ln438_8_reg_1715 <= select_ln438_8_fu_1399_p3;
        select_ln438_9_reg_1720 <= select_ln438_9_fu_1527_p3;
        select_ln438_reg_1675 <= select_ln438_fu_375_p3;
    end
end

always @ (*) begin
    if ((((ap_start == 1'b0) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1)) | ((ap_enable_reg_pp0_iter2 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0_0to1 = 1'b1;
    end else begin
        ap_idle_pp0_0to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (ap_idle_pp0_0to1 == 1'b1))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table_ce0 = 1'b1;
    end else begin
        tanh_table_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table_ce1 = 1'b1;
    end else begin
        tanh_table_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table_ce2 = 1'b1;
    end else begin
        tanh_table_ce2 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table_ce3 = 1'b1;
    end else begin
        tanh_table_ce3 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table_ce4 = 1'b1;
    end else begin
        tanh_table_ce4 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table_ce5 = 1'b1;
    end else begin
        tanh_table_ce5 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table_ce6 = 1'b1;
    end else begin
        tanh_table_ce6 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table_ce7 = 1'b1;
    end else begin
        tanh_table_ce7 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table_ce8 = 1'b1;
    end else begin
        tanh_table_ce8 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        tanh_table_ce9 = 1'b1;
    end else begin
        tanh_table_ce9 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln434_1_fu_455_p2 = (select_ln545_1_fu_443_p3 + 14'd512);

assign add_ln434_2_fu_583_p2 = (select_ln545_2_fu_571_p3 + 14'd512);

assign add_ln434_3_fu_711_p2 = (select_ln545_3_fu_699_p3 + 14'd512);

assign add_ln434_4_fu_839_p2 = (select_ln545_4_fu_827_p3 + 14'd512);

assign add_ln434_5_fu_967_p2 = (select_ln545_5_fu_955_p3 + 14'd512);

assign add_ln434_6_fu_1095_p2 = (select_ln545_6_fu_1083_p3 + 14'd512);

assign add_ln434_7_fu_1223_p2 = (select_ln545_7_fu_1211_p3 + 14'd512);

assign add_ln434_8_fu_1351_p2 = (select_ln545_8_fu_1339_p3 + 14'd512);

assign add_ln434_9_fu_1479_p2 = (select_ln545_9_fu_1467_p3 + 14'd512);

assign add_ln434_fu_327_p2 = (select_ln545_fu_315_p3 + 14'd512);

assign add_ln436_1_fu_461_p2 = (trunc_ln434_1_fu_451_p1 + 13'd512);

assign add_ln436_2_fu_589_p2 = (trunc_ln434_2_fu_579_p1 + 13'd512);

assign add_ln436_3_fu_717_p2 = (trunc_ln434_3_fu_707_p1 + 13'd512);

assign add_ln436_4_fu_845_p2 = (trunc_ln434_4_fu_835_p1 + 13'd512);

assign add_ln436_5_fu_973_p2 = (trunc_ln434_5_fu_963_p1 + 13'd512);

assign add_ln436_6_fu_1101_p2 = (trunc_ln434_6_fu_1091_p1 + 13'd512);

assign add_ln436_7_fu_1229_p2 = (trunc_ln434_7_fu_1219_p1 + 13'd512);

assign add_ln436_8_fu_1357_p2 = (trunc_ln434_8_fu_1347_p1 + 13'd512);

assign add_ln436_9_fu_1485_p2 = (trunc_ln434_9_fu_1475_p1 + 13'd512);

assign add_ln436_fu_333_p2 = (trunc_ln434_fu_323_p1 + 13'd512);

assign add_ln691_1_fu_429_p2 = ($signed(sext_ln850_1_fu_401_p1) + $signed(14'd1));

assign add_ln691_2_fu_557_p2 = ($signed(sext_ln850_2_fu_529_p1) + $signed(14'd1));

assign add_ln691_3_fu_685_p2 = ($signed(sext_ln850_3_fu_657_p1) + $signed(14'd1));

assign add_ln691_4_fu_813_p2 = ($signed(sext_ln850_4_fu_785_p1) + $signed(14'd1));

assign add_ln691_5_fu_941_p2 = ($signed(sext_ln850_5_fu_913_p1) + $signed(14'd1));

assign add_ln691_6_fu_1069_p2 = ($signed(sext_ln850_6_fu_1041_p1) + $signed(14'd1));

assign add_ln691_7_fu_1197_p2 = ($signed(sext_ln850_7_fu_1169_p1) + $signed(14'd1));

assign add_ln691_8_fu_1325_p2 = ($signed(sext_ln850_8_fu_1297_p1) + $signed(14'd1));

assign add_ln691_9_fu_1453_p2 = ($signed(sext_ln850_9_fu_1425_p1) + $signed(14'd1));

assign add_ln691_fu_301_p2 = ($signed(sext_ln850_fu_273_p1) + $signed(14'd1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start;

assign ap_return_0 = sext_ln703_fu_1575_p1;

assign ap_return_1 = sext_ln703_1_fu_1579_p1;

assign ap_return_2 = sext_ln703_2_fu_1583_p1;

assign ap_return_3 = sext_ln703_3_fu_1587_p1;

assign ap_return_4 = sext_ln703_4_fu_1591_p1;

assign ap_return_5 = sext_ln703_5_fu_1595_p1;

assign ap_return_6 = sext_ln703_6_fu_1599_p1;

assign ap_return_7 = sext_ln703_7_fu_1603_p1;

assign ap_return_8 = sext_ln703_8_fu_1607_p1;

assign ap_return_9 = sext_ln703_9_fu_1611_p1;

assign icmp_ln438_1_fu_497_p2 = ((tmp_7_fu_487_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln438_2_fu_625_p2 = ((tmp_10_fu_615_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln438_3_fu_753_p2 = ((tmp_14_fu_743_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln438_4_fu_881_p2 = ((tmp_18_fu_871_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln438_5_fu_1009_p2 = ((tmp_20_fu_999_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln438_6_fu_1137_p2 = ((tmp_22_fu_1127_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln438_7_fu_1265_p2 = ((tmp_24_fu_1255_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln438_8_fu_1393_p2 = ((tmp_26_fu_1383_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln438_9_fu_1521_p2 = ((tmp_28_fu_1511_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln438_fu_369_p2 = ((tmp_3_fu_359_p4 != 3'd0) ? 1'b1 : 1'b0);

assign icmp_ln850_1_fu_405_p2 = (($signed(shl_ln1118_1_fu_383_p3) < $signed(26'd67108857)) ? 1'b1 : 1'b0);

assign icmp_ln850_2_fu_533_p2 = (($signed(shl_ln1118_2_fu_511_p3) < $signed(26'd67108857)) ? 1'b1 : 1'b0);

assign icmp_ln850_3_fu_661_p2 = (($signed(shl_ln1118_3_fu_639_p3) < $signed(26'd67108857)) ? 1'b1 : 1'b0);

assign icmp_ln850_4_fu_789_p2 = (($signed(shl_ln1118_4_fu_767_p3) < $signed(26'd67108857)) ? 1'b1 : 1'b0);

assign icmp_ln850_5_fu_917_p2 = (($signed(shl_ln1118_5_fu_895_p3) < $signed(26'd67108857)) ? 1'b1 : 1'b0);

assign icmp_ln850_6_fu_1045_p2 = (($signed(shl_ln1118_6_fu_1023_p3) < $signed(26'd67108857)) ? 1'b1 : 1'b0);

assign icmp_ln850_7_fu_1173_p2 = (($signed(shl_ln1118_7_fu_1151_p3) < $signed(26'd67108857)) ? 1'b1 : 1'b0);

assign icmp_ln850_8_fu_1301_p2 = (($signed(shl_ln1118_8_fu_1279_p3) < $signed(26'd67108857)) ? 1'b1 : 1'b0);

assign icmp_ln850_9_fu_1429_p2 = (($signed(shl_ln1118_9_fu_1407_p3) < $signed(26'd67108857)) ? 1'b1 : 1'b0);

assign icmp_ln850_fu_277_p2 = (($signed(shl_ln_fu_255_p3) < $signed(26'd67108857)) ? 1'b1 : 1'b0);

assign icmp_ln851_1_fu_423_p2 = ((p_Result_2_1_fu_415_p3 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_2_fu_551_p2 = ((p_Result_2_2_fu_543_p3 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_3_fu_679_p2 = ((p_Result_2_3_fu_671_p3 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_4_fu_807_p2 = ((p_Result_2_4_fu_799_p3 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_5_fu_935_p2 = ((p_Result_2_5_fu_927_p3 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_6_fu_1063_p2 = ((p_Result_2_6_fu_1055_p3 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_7_fu_1191_p2 = ((p_Result_2_7_fu_1183_p3 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_8_fu_1319_p2 = ((p_Result_2_8_fu_1311_p3 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_9_fu_1447_p2 = ((p_Result_2_9_fu_1439_p3 != 10'd0) ? 1'b1 : 1'b0);

assign icmp_ln851_fu_295_p2 = ((p_Result_2_fu_287_p3 != 10'd0) ? 1'b1 : 1'b0);

assign p_Result_2_1_fu_415_p3 = {{trunc_ln851_1_fu_411_p1}, {7'd0}};

assign p_Result_2_2_fu_543_p3 = {{trunc_ln851_2_fu_539_p1}, {7'd0}};

assign p_Result_2_3_fu_671_p3 = {{trunc_ln851_3_fu_667_p1}, {7'd0}};

assign p_Result_2_4_fu_799_p3 = {{trunc_ln851_4_fu_795_p1}, {7'd0}};

assign p_Result_2_5_fu_927_p3 = {{trunc_ln851_5_fu_923_p1}, {7'd0}};

assign p_Result_2_6_fu_1055_p3 = {{trunc_ln851_6_fu_1051_p1}, {7'd0}};

assign p_Result_2_7_fu_1183_p3 = {{trunc_ln851_7_fu_1179_p1}, {7'd0}};

assign p_Result_2_8_fu_1311_p3 = {{trunc_ln851_8_fu_1307_p1}, {7'd0}};

assign p_Result_2_9_fu_1439_p3 = {{trunc_ln851_9_fu_1435_p1}, {7'd0}};

assign p_Result_2_fu_287_p3 = {{trunc_ln851_fu_283_p1}, {7'd0}};

assign select_ln436_1_fu_475_p3 = ((tmp_5_fu_467_p3[0:0] == 1'b1) ? 13'd0 : add_ln436_1_fu_461_p2);

assign select_ln436_2_fu_603_p3 = ((tmp_9_fu_595_p3[0:0] == 1'b1) ? 13'd0 : add_ln436_2_fu_589_p2);

assign select_ln436_3_fu_731_p3 = ((tmp_12_fu_723_p3[0:0] == 1'b1) ? 13'd0 : add_ln436_3_fu_717_p2);

assign select_ln436_4_fu_859_p3 = ((tmp_16_fu_851_p3[0:0] == 1'b1) ? 13'd0 : add_ln436_4_fu_845_p2);

assign select_ln436_5_fu_987_p3 = ((tmp_19_fu_979_p3[0:0] == 1'b1) ? 13'd0 : add_ln436_5_fu_973_p2);

assign select_ln436_6_fu_1115_p3 = ((tmp_21_fu_1107_p3[0:0] == 1'b1) ? 13'd0 : add_ln436_6_fu_1101_p2);

assign select_ln436_7_fu_1243_p3 = ((tmp_23_fu_1235_p3[0:0] == 1'b1) ? 13'd0 : add_ln436_7_fu_1229_p2);

assign select_ln436_8_fu_1371_p3 = ((tmp_25_fu_1363_p3[0:0] == 1'b1) ? 13'd0 : add_ln436_8_fu_1357_p2);

assign select_ln436_9_fu_1499_p3 = ((tmp_27_fu_1491_p3[0:0] == 1'b1) ? 13'd0 : add_ln436_9_fu_1485_p2);

assign select_ln436_fu_347_p3 = ((tmp_1_fu_339_p3[0:0] == 1'b1) ? 13'd0 : add_ln436_fu_333_p2);

assign select_ln438_1_fu_503_p3 = ((icmp_ln438_1_fu_497_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln438_1_fu_483_p1);

assign select_ln438_2_fu_631_p3 = ((icmp_ln438_2_fu_625_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln438_2_fu_611_p1);

assign select_ln438_3_fu_759_p3 = ((icmp_ln438_3_fu_753_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln438_3_fu_739_p1);

assign select_ln438_4_fu_887_p3 = ((icmp_ln438_4_fu_881_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln438_4_fu_867_p1);

assign select_ln438_5_fu_1015_p3 = ((icmp_ln438_5_fu_1009_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln438_5_fu_995_p1);

assign select_ln438_6_fu_1143_p3 = ((icmp_ln438_6_fu_1137_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln438_6_fu_1123_p1);

assign select_ln438_7_fu_1271_p3 = ((icmp_ln438_7_fu_1265_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln438_7_fu_1251_p1);

assign select_ln438_8_fu_1399_p3 = ((icmp_ln438_8_fu_1393_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln438_8_fu_1379_p1);

assign select_ln438_9_fu_1527_p3 = ((icmp_ln438_9_fu_1521_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln438_9_fu_1507_p1);

assign select_ln438_fu_375_p3 = ((icmp_ln438_fu_369_p2[0:0] == 1'b1) ? 10'd1023 : trunc_ln438_fu_355_p1);

assign select_ln545_1_fu_443_p3 = ((icmp_ln850_1_fu_405_p2[0:0] == 1'b1) ? select_ln850_1_fu_435_p3 : sext_ln850_1_fu_401_p1);

assign select_ln545_2_fu_571_p3 = ((icmp_ln850_2_fu_533_p2[0:0] == 1'b1) ? select_ln850_2_fu_563_p3 : sext_ln850_2_fu_529_p1);

assign select_ln545_3_fu_699_p3 = ((icmp_ln850_3_fu_661_p2[0:0] == 1'b1) ? select_ln850_3_fu_691_p3 : sext_ln850_3_fu_657_p1);

assign select_ln545_4_fu_827_p3 = ((icmp_ln850_4_fu_789_p2[0:0] == 1'b1) ? select_ln850_4_fu_819_p3 : sext_ln850_4_fu_785_p1);

assign select_ln545_5_fu_955_p3 = ((icmp_ln850_5_fu_917_p2[0:0] == 1'b1) ? select_ln850_5_fu_947_p3 : sext_ln850_5_fu_913_p1);

assign select_ln545_6_fu_1083_p3 = ((icmp_ln850_6_fu_1045_p2[0:0] == 1'b1) ? select_ln850_6_fu_1075_p3 : sext_ln850_6_fu_1041_p1);

assign select_ln545_7_fu_1211_p3 = ((icmp_ln850_7_fu_1173_p2[0:0] == 1'b1) ? select_ln850_7_fu_1203_p3 : sext_ln850_7_fu_1169_p1);

assign select_ln545_8_fu_1339_p3 = ((icmp_ln850_8_fu_1301_p2[0:0] == 1'b1) ? select_ln850_8_fu_1331_p3 : sext_ln850_8_fu_1297_p1);

assign select_ln545_9_fu_1467_p3 = ((icmp_ln850_9_fu_1429_p2[0:0] == 1'b1) ? select_ln850_9_fu_1459_p3 : sext_ln850_9_fu_1425_p1);

assign select_ln545_fu_315_p3 = ((icmp_ln850_fu_277_p2[0:0] == 1'b1) ? select_ln850_fu_307_p3 : sext_ln850_fu_273_p1);

assign select_ln850_1_fu_435_p3 = ((icmp_ln851_1_fu_423_p2[0:0] == 1'b1) ? add_ln691_1_fu_429_p2 : sext_ln850_1_fu_401_p1);

assign select_ln850_2_fu_563_p3 = ((icmp_ln851_2_fu_551_p2[0:0] == 1'b1) ? add_ln691_2_fu_557_p2 : sext_ln850_2_fu_529_p1);

assign select_ln850_3_fu_691_p3 = ((icmp_ln851_3_fu_679_p2[0:0] == 1'b1) ? add_ln691_3_fu_685_p2 : sext_ln850_3_fu_657_p1);

assign select_ln850_4_fu_819_p3 = ((icmp_ln851_4_fu_807_p2[0:0] == 1'b1) ? add_ln691_4_fu_813_p2 : sext_ln850_4_fu_785_p1);

assign select_ln850_5_fu_947_p3 = ((icmp_ln851_5_fu_935_p2[0:0] == 1'b1) ? add_ln691_5_fu_941_p2 : sext_ln850_5_fu_913_p1);

assign select_ln850_6_fu_1075_p3 = ((icmp_ln851_6_fu_1063_p2[0:0] == 1'b1) ? add_ln691_6_fu_1069_p2 : sext_ln850_6_fu_1041_p1);

assign select_ln850_7_fu_1203_p3 = ((icmp_ln851_7_fu_1191_p2[0:0] == 1'b1) ? add_ln691_7_fu_1197_p2 : sext_ln850_7_fu_1169_p1);

assign select_ln850_8_fu_1331_p3 = ((icmp_ln851_8_fu_1319_p2[0:0] == 1'b1) ? add_ln691_8_fu_1325_p2 : sext_ln850_8_fu_1297_p1);

assign select_ln850_9_fu_1459_p3 = ((icmp_ln851_9_fu_1447_p2[0:0] == 1'b1) ? add_ln691_9_fu_1453_p2 : sext_ln850_9_fu_1425_p1);

assign select_ln850_fu_307_p3 = ((icmp_ln851_fu_295_p2[0:0] == 1'b1) ? add_ln691_fu_301_p2 : sext_ln850_fu_273_p1);

assign sext_ln703_1_fu_1579_p1 = $signed(tanh_table_q8);

assign sext_ln703_2_fu_1583_p1 = $signed(tanh_table_q7);

assign sext_ln703_3_fu_1587_p1 = $signed(tanh_table_q6);

assign sext_ln703_4_fu_1591_p1 = $signed(tanh_table_q5);

assign sext_ln703_5_fu_1595_p1 = $signed(tanh_table_q4);

assign sext_ln703_6_fu_1599_p1 = $signed(tanh_table_q3);

assign sext_ln703_7_fu_1603_p1 = $signed(tanh_table_q2);

assign sext_ln703_8_fu_1607_p1 = $signed(tanh_table_q1);

assign sext_ln703_9_fu_1611_p1 = $signed(tanh_table_q0);

assign sext_ln703_fu_1575_p1 = $signed(tanh_table_q9);

assign sext_ln850_1_fu_401_p1 = $signed(tmp_2_fu_391_p4);

assign sext_ln850_2_fu_529_p1 = $signed(tmp_4_fu_519_p4);

assign sext_ln850_3_fu_657_p1 = $signed(tmp_6_fu_647_p4);

assign sext_ln850_4_fu_785_p1 = $signed(tmp_8_fu_775_p4);

assign sext_ln850_5_fu_913_p1 = $signed(tmp_s_fu_903_p4);

assign sext_ln850_6_fu_1041_p1 = $signed(tmp_11_fu_1031_p4);

assign sext_ln850_7_fu_1169_p1 = $signed(tmp_13_fu_1159_p4);

assign sext_ln850_8_fu_1297_p1 = $signed(tmp_15_fu_1287_p4);

assign sext_ln850_9_fu_1425_p1 = $signed(tmp_17_fu_1415_p4);

assign sext_ln850_fu_273_p1 = $signed(tmp_fu_263_p4);

assign shl_ln1118_1_fu_383_p3 = {{p_read1}, {10'd0}};

assign shl_ln1118_2_fu_511_p3 = {{p_read2}, {10'd0}};

assign shl_ln1118_3_fu_639_p3 = {{p_read3}, {10'd0}};

assign shl_ln1118_4_fu_767_p3 = {{p_read4}, {10'd0}};

assign shl_ln1118_5_fu_895_p3 = {{p_read5}, {10'd0}};

assign shl_ln1118_6_fu_1023_p3 = {{p_read6}, {10'd0}};

assign shl_ln1118_7_fu_1151_p3 = {{p_read7}, {10'd0}};

assign shl_ln1118_8_fu_1279_p3 = {{p_read8}, {10'd0}};

assign shl_ln1118_9_fu_1407_p3 = {{p_read9}, {10'd0}};

assign shl_ln_fu_255_p3 = {{p_read}, {10'd0}};

assign tanh_table_address0 = zext_ln440_9_fu_1571_p1;

assign tanh_table_address1 = zext_ln440_8_fu_1567_p1;

assign tanh_table_address2 = zext_ln440_7_fu_1563_p1;

assign tanh_table_address3 = zext_ln440_6_fu_1559_p1;

assign tanh_table_address4 = zext_ln440_5_fu_1555_p1;

assign tanh_table_address5 = zext_ln440_4_fu_1551_p1;

assign tanh_table_address6 = zext_ln440_3_fu_1547_p1;

assign tanh_table_address7 = zext_ln440_2_fu_1543_p1;

assign tanh_table_address8 = zext_ln440_1_fu_1539_p1;

assign tanh_table_address9 = zext_ln440_fu_1535_p1;

assign tmp_10_fu_615_p4 = {{select_ln436_2_fu_603_p3[12:10]}};

assign tmp_11_fu_1031_p4 = {{p_read6[15:3]}};

assign tmp_12_fu_723_p3 = add_ln434_3_fu_711_p2[32'd13];

assign tmp_13_fu_1159_p4 = {{p_read7[15:3]}};

assign tmp_14_fu_743_p4 = {{select_ln436_3_fu_731_p3[12:10]}};

assign tmp_15_fu_1287_p4 = {{p_read8[15:3]}};

assign tmp_16_fu_851_p3 = add_ln434_4_fu_839_p2[32'd13];

assign tmp_17_fu_1415_p4 = {{p_read9[15:3]}};

assign tmp_18_fu_871_p4 = {{select_ln436_4_fu_859_p3[12:10]}};

assign tmp_19_fu_979_p3 = add_ln434_5_fu_967_p2[32'd13];

assign tmp_1_fu_339_p3 = add_ln434_fu_327_p2[32'd13];

assign tmp_20_fu_999_p4 = {{select_ln436_5_fu_987_p3[12:10]}};

assign tmp_21_fu_1107_p3 = add_ln434_6_fu_1095_p2[32'd13];

assign tmp_22_fu_1127_p4 = {{select_ln436_6_fu_1115_p3[12:10]}};

assign tmp_23_fu_1235_p3 = add_ln434_7_fu_1223_p2[32'd13];

assign tmp_24_fu_1255_p4 = {{select_ln436_7_fu_1243_p3[12:10]}};

assign tmp_25_fu_1363_p3 = add_ln434_8_fu_1351_p2[32'd13];

assign tmp_26_fu_1383_p4 = {{select_ln436_8_fu_1371_p3[12:10]}};

assign tmp_27_fu_1491_p3 = add_ln434_9_fu_1479_p2[32'd13];

assign tmp_28_fu_1511_p4 = {{select_ln436_9_fu_1499_p3[12:10]}};

assign tmp_2_fu_391_p4 = {{p_read1[15:3]}};

assign tmp_3_fu_359_p4 = {{select_ln436_fu_347_p3[12:10]}};

assign tmp_4_fu_519_p4 = {{p_read2[15:3]}};

assign tmp_5_fu_467_p3 = add_ln434_1_fu_455_p2[32'd13];

assign tmp_6_fu_647_p4 = {{p_read3[15:3]}};

assign tmp_7_fu_487_p4 = {{select_ln436_1_fu_475_p3[12:10]}};

assign tmp_8_fu_775_p4 = {{p_read4[15:3]}};

assign tmp_9_fu_595_p3 = add_ln434_2_fu_583_p2[32'd13];

assign tmp_fu_263_p4 = {{p_read[15:3]}};

assign tmp_s_fu_903_p4 = {{p_read5[15:3]}};

assign trunc_ln434_1_fu_451_p1 = select_ln545_1_fu_443_p3[12:0];

assign trunc_ln434_2_fu_579_p1 = select_ln545_2_fu_571_p3[12:0];

assign trunc_ln434_3_fu_707_p1 = select_ln545_3_fu_699_p3[12:0];

assign trunc_ln434_4_fu_835_p1 = select_ln545_4_fu_827_p3[12:0];

assign trunc_ln434_5_fu_963_p1 = select_ln545_5_fu_955_p3[12:0];

assign trunc_ln434_6_fu_1091_p1 = select_ln545_6_fu_1083_p3[12:0];

assign trunc_ln434_7_fu_1219_p1 = select_ln545_7_fu_1211_p3[12:0];

assign trunc_ln434_8_fu_1347_p1 = select_ln545_8_fu_1339_p3[12:0];

assign trunc_ln434_9_fu_1475_p1 = select_ln545_9_fu_1467_p3[12:0];

assign trunc_ln434_fu_323_p1 = select_ln545_fu_315_p3[12:0];

assign trunc_ln438_1_fu_483_p1 = select_ln436_1_fu_475_p3[9:0];

assign trunc_ln438_2_fu_611_p1 = select_ln436_2_fu_603_p3[9:0];

assign trunc_ln438_3_fu_739_p1 = select_ln436_3_fu_731_p3[9:0];

assign trunc_ln438_4_fu_867_p1 = select_ln436_4_fu_859_p3[9:0];

assign trunc_ln438_5_fu_995_p1 = select_ln436_5_fu_987_p3[9:0];

assign trunc_ln438_6_fu_1123_p1 = select_ln436_6_fu_1115_p3[9:0];

assign trunc_ln438_7_fu_1251_p1 = select_ln436_7_fu_1243_p3[9:0];

assign trunc_ln438_8_fu_1379_p1 = select_ln436_8_fu_1371_p3[9:0];

assign trunc_ln438_9_fu_1507_p1 = select_ln436_9_fu_1499_p3[9:0];

assign trunc_ln438_fu_355_p1 = select_ln436_fu_347_p3[9:0];

assign trunc_ln851_1_fu_411_p1 = p_read1[2:0];

assign trunc_ln851_2_fu_539_p1 = p_read2[2:0];

assign trunc_ln851_3_fu_667_p1 = p_read3[2:0];

assign trunc_ln851_4_fu_795_p1 = p_read4[2:0];

assign trunc_ln851_5_fu_923_p1 = p_read5[2:0];

assign trunc_ln851_6_fu_1051_p1 = p_read6[2:0];

assign trunc_ln851_7_fu_1179_p1 = p_read7[2:0];

assign trunc_ln851_8_fu_1307_p1 = p_read8[2:0];

assign trunc_ln851_9_fu_1435_p1 = p_read9[2:0];

assign trunc_ln851_fu_283_p1 = p_read[2:0];

assign zext_ln440_1_fu_1539_p1 = select_ln438_1_reg_1680;

assign zext_ln440_2_fu_1543_p1 = select_ln438_2_reg_1685;

assign zext_ln440_3_fu_1547_p1 = select_ln438_3_reg_1690;

assign zext_ln440_4_fu_1551_p1 = select_ln438_4_reg_1695;

assign zext_ln440_5_fu_1555_p1 = select_ln438_5_reg_1700;

assign zext_ln440_6_fu_1559_p1 = select_ln438_6_reg_1705;

assign zext_ln440_7_fu_1563_p1 = select_ln438_7_reg_1710;

assign zext_ln440_8_fu_1567_p1 = select_ln438_8_reg_1715;

assign zext_ln440_9_fu_1571_p1 = select_ln438_9_reg_1720;

assign zext_ln440_fu_1535_p1 = select_ln438_reg_1675;

endmodule //myproject_tanh_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_tanh_config3_s
