// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        dense_input_address0,
        dense_input_ce0,
        dense_input_q0,
        dense_input_address1,
        dense_input_ce1,
        dense_input_q1,
        ap_return_0,
        ap_return_1,
        ap_return_2,
        ap_return_3,
        ap_return_4,
        ap_return_5,
        ap_return_6,
        ap_return_7,
        ap_return_8,
        ap_return_9
);

parameter    ap_ST_fsm_pp0_stage0 = 5'd1;
parameter    ap_ST_fsm_pp0_stage1 = 5'd2;
parameter    ap_ST_fsm_pp0_stage2 = 5'd4;
parameter    ap_ST_fsm_pp0_stage3 = 5'd8;
parameter    ap_ST_fsm_pp0_stage4 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [3:0] dense_input_address0;
output   dense_input_ce0;
input  [15:0] dense_input_q0;
output  [3:0] dense_input_address1;
output   dense_input_ce1;
input  [15:0] dense_input_q1;
output  [15:0] ap_return_0;
output  [15:0] ap_return_1;
output  [15:0] ap_return_2;
output  [15:0] ap_return_3;
output  [15:0] ap_return_4;
output  [15:0] ap_return_5;
output  [15:0] ap_return_6;
output  [15:0] ap_return_7;
output  [15:0] ap_return_8;
output  [15:0] ap_return_9;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg[3:0] dense_input_address0;
reg dense_input_ce0;
reg[3:0] dense_input_address1;
reg dense_input_ce1;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
wire    ap_block_pp0_stage0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_state5_pp0_stage4_iter0;
wire    ap_block_pp0_stage4_11001;
reg  signed [15:0] reg_26630;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_state3_pp0_stage2_iter0;
wire    ap_block_pp0_stage2_11001;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state6_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_11001;
reg  signed [15:0] dense_input_load_reg_28857;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_state2_pp0_stage1_iter0;
wire    ap_block_state7_pp0_stage1_iter1;
wire    ap_block_pp0_stage1_11001;
reg  signed [15:0] dense_input_load_1_reg_28867;
reg   [15:0] trunc_ln708_19_reg_28887;
reg   [15:0] trunc_ln708_20_reg_28892;
reg   [15:0] trunc_ln708_21_reg_28897;
reg   [15:0] trunc_ln708_22_reg_28902;
reg   [15:0] trunc_ln708_23_reg_28907;
reg   [15:0] trunc_ln708_24_reg_28912;
reg   [15:0] trunc_ln708_25_reg_28917;
reg   [14:0] trunc_ln708_26_reg_28922;
reg   [15:0] trunc_ln708_27_reg_28927;
reg   [15:0] trunc_ln708_28_reg_28932;
reg   [15:0] trunc_ln708_29_reg_28937;
reg   [12:0] trunc_ln708_31_reg_28942;
reg   [15:0] trunc_ln708_32_reg_28947;
reg   [15:0] trunc_ln708_33_reg_28952;
reg   [15:0] trunc_ln708_35_reg_28957;
reg   [12:0] trunc_ln708_36_reg_28962;
reg   [12:0] trunc_ln708_37_reg_28967;
reg   [15:0] trunc_ln708_38_reg_28972;
reg   [14:0] trunc_ln708_49_reg_28987;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_state4_pp0_stage3_iter0;
wire    ap_block_pp0_stage3_11001;
reg   [14:0] trunc_ln708_50_reg_28992;
reg   [10:0] trunc_ln708_51_reg_28997;
reg   [14:0] trunc_ln708_52_reg_29002;
reg   [15:0] trunc_ln708_53_reg_29007;
reg   [15:0] trunc_ln708_54_reg_29012;
reg   [15:0] trunc_ln708_55_reg_29017;
reg   [15:0] trunc_ln708_56_reg_29022;
reg   [12:0] trunc_ln708_57_reg_29027;
reg   [15:0] trunc_ln708_58_reg_29032;
wire   [15:0] add_ln703_10_fu_27262_p2;
reg   [15:0] add_ln703_10_reg_29047;
wire   [15:0] add_ln703_19_fu_27273_p2;
reg   [15:0] add_ln703_19_reg_29052;
wire   [15:0] add_ln703_28_fu_27284_p2;
reg   [15:0] add_ln703_28_reg_29057;
wire   [15:0] add_ln703_37_fu_27294_p2;
reg   [15:0] add_ln703_37_reg_29062;
wire   [15:0] add_ln703_46_fu_27304_p2;
reg   [15:0] add_ln703_46_reg_29067;
wire   [15:0] add_ln703_55_fu_27315_p2;
reg   [15:0] add_ln703_55_reg_29072;
wire   [15:0] add_ln703_64_fu_27325_p2;
reg   [15:0] add_ln703_64_reg_29077;
wire   [15:0] add_ln703_73_fu_27336_p2;
reg   [15:0] add_ln703_73_reg_29082;
wire   [15:0] add_ln703_82_fu_27348_p2;
reg   [15:0] add_ln703_82_reg_29087;
wire   [15:0] add_ln703_91_fu_27358_p2;
reg   [15:0] add_ln703_91_reg_29092;
reg   [15:0] trunc_ln708_59_reg_29097;
reg   [13:0] trunc_ln708_60_reg_29102;
reg   [15:0] trunc_ln708_61_reg_29107;
reg   [13:0] trunc_ln708_64_reg_29112;
reg   [15:0] trunc_ln708_65_reg_29117;
reg   [15:0] trunc_ln708_66_reg_29122;
reg   [15:0] trunc_ln708_67_reg_29127;
reg  signed [15:0] dense_input_load_7_reg_29132;
reg   [15:0] trunc_ln708_70_reg_29139;
reg   [15:0] trunc_ln708_71_reg_29144;
reg   [15:0] trunc_ln708_72_reg_29149;
reg   [15:0] trunc_ln708_73_reg_29154;
reg   [13:0] trunc_ln708_74_reg_29159;
reg   [15:0] trunc_ln708_76_reg_29164;
reg   [15:0] trunc_ln708_77_reg_29169;
reg   [15:0] trunc_ln708_78_reg_29174;
wire   [15:0] add_ln703_14_fu_27898_p2;
reg   [15:0] add_ln703_14_reg_29189;
wire   [15:0] add_ln703_23_fu_27910_p2;
reg   [15:0] add_ln703_23_reg_29194;
wire   [15:0] add_ln703_32_fu_27921_p2;
reg   [15:0] add_ln703_32_reg_29199;
wire   [15:0] add_ln703_41_fu_27932_p2;
reg   [15:0] add_ln703_41_reg_29204;
wire   [15:0] add_ln703_50_fu_27943_p2;
reg   [15:0] add_ln703_50_reg_29209;
wire   [15:0] add_ln703_59_fu_27954_p2;
reg   [15:0] add_ln703_59_reg_29214;
wire   [15:0] add_ln703_68_fu_27966_p2;
reg   [15:0] add_ln703_68_reg_29219;
wire   [15:0] add_ln703_77_fu_27978_p2;
reg   [15:0] add_ln703_77_reg_29224;
wire   [15:0] add_ln703_86_fu_27989_p2;
reg   [15:0] add_ln703_86_reg_29229;
wire   [15:0] add_ln703_95_fu_28000_p2;
reg   [15:0] add_ln703_95_reg_29234;
reg    ap_enable_reg_pp0_iter0_reg;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage1;
wire    ap_block_pp0_stage2;
wire    ap_block_pp0_stage3;
wire    ap_block_pp0_stage4;
wire  signed [15:0] mul_ln708_5_fu_373_p0;
wire  signed [25:0] sext_ln1118_45_fu_27625_p1;
wire  signed [10:0] mul_ln708_5_fu_373_p1;
wire  signed [7:0] mul_ln1118_33_fu_374_p1;
wire  signed [15:0] mul_ln708_fu_375_p0;
wire  signed [25:0] sext_ln1118_fu_28005_p1;
wire   [10:0] mul_ln708_fu_375_p1;
wire  signed [15:0] mul_ln1118_69_fu_377_p0;
wire  signed [25:0] sext_ln1118_48_fu_27757_p1;
wire   [9:0] mul_ln1118_69_fu_377_p1;
wire  signed [15:0] mul_ln1118_42_fu_378_p0;
wire  signed [25:0] sext_ln1118_26_fu_27105_p1;
wire   [9:0] mul_ln1118_42_fu_378_p1;
wire  signed [15:0] mul_ln1118_19_fu_379_p0;
wire  signed [25:0] sext_ln1118_13_fu_26635_p1;
wire  signed [9:0] mul_ln1118_19_fu_379_p1;
wire  signed [15:0] mul_ln1118_7_fu_380_p0;
wire  signed [25:0] sext_ln1118_7_fu_28179_p1;
wire   [9:0] mul_ln1118_7_fu_380_p1;
wire  signed [15:0] mul_ln1118_40_fu_381_p0;
wire  signed [24:0] sext_ln1118_27_fu_27114_p1;
wire   [8:0] mul_ln1118_40_fu_381_p1;
wire  signed [15:0] mul_ln1118_25_fu_382_p0;
wire  signed [22:0] sext_ln1118_16_fu_26778_p1;
wire   [6:0] mul_ln1118_25_fu_382_p1;
wire  signed [6:0] mul_ln1118_37_fu_384_p1;
wire  signed [15:0] mul_ln1118_1_fu_385_p0;
wire  signed [9:0] mul_ln1118_1_fu_385_p1;
wire  signed [15:0] mul_ln708_1_fu_386_p0;
wire   [10:0] mul_ln708_1_fu_386_p1;
wire  signed [15:0] mul_ln1118_24_fu_387_p0;
wire  signed [25:0] sext_ln1118_17_fu_26785_p1;
wire   [9:0] mul_ln1118_24_fu_387_p1;
wire   [7:0] mul_ln1118_58_fu_388_p1;
wire  signed [15:0] mul_ln1118_23_fu_389_p0;
wire  signed [9:0] mul_ln1118_23_fu_389_p1;
wire  signed [15:0] mul_ln1118_12_fu_390_p0;
wire  signed [24:0] sext_ln1118_8_fu_28186_p1;
wire   [8:0] mul_ln1118_12_fu_390_p1;
wire  signed [15:0] mul_ln1118_75_fu_391_p0;
wire  signed [24:0] sext_ln1118_46_fu_27742_p1;
wire  signed [8:0] mul_ln1118_75_fu_391_p1;
wire  signed [15:0] mul_ln1118_43_fu_392_p0;
wire  signed [9:0] mul_ln1118_43_fu_392_p1;
wire  signed [15:0] mul_ln1118_57_fu_394_p0;
wire  signed [25:0] sext_ln1118_39_fu_27453_p1;
wire  signed [9:0] mul_ln1118_57_fu_394_p1;
wire  signed [15:0] mul_ln1118_54_fu_395_p0;
wire  signed [9:0] mul_ln1118_54_fu_395_p1;
wire  signed [15:0] mul_ln1118_50_fu_396_p0;
wire  signed [23:0] sext_ln1118_30_fu_27363_p1;
wire   [7:0] mul_ln1118_50_fu_396_p1;
wire  signed [15:0] mul_ln1118_13_fu_398_p0;
wire  signed [9:0] mul_ln1118_13_fu_398_p1;
wire  signed [15:0] mul_ln1118_5_fu_399_p0;
wire  signed [9:0] mul_ln1118_5_fu_399_p1;
wire  signed [15:0] mul_ln1118_71_fu_401_p0;
wire   [8:0] mul_ln1118_71_fu_401_p1;
wire  signed [15:0] mul_ln1118_66_fu_402_p0;
wire   [9:0] mul_ln1118_66_fu_402_p1;
wire  signed [15:0] mul_ln1118_65_fu_403_p0;
wire  signed [9:0] mul_ln1118_65_fu_403_p1;
wire  signed [15:0] mul_ln1118_28_fu_404_p0;
wire  signed [25:0] sext_ln1118_24_fu_26980_p1;
wire  signed [9:0] mul_ln1118_28_fu_404_p1;
wire  signed [15:0] mul_ln1118_67_fu_405_p0;
wire  signed [9:0] mul_ln1118_67_fu_405_p1;
wire  signed [15:0] mul_ln1118_31_fu_406_p0;
wire   [9:0] mul_ln1118_31_fu_406_p1;
wire  signed [15:0] mul_ln1118_17_fu_407_p0;
wire   [9:0] mul_ln1118_17_fu_407_p1;
wire  signed [15:0] mul_ln1118_22_fu_408_p0;
wire  signed [9:0] mul_ln1118_22_fu_408_p1;
wire  signed [15:0] mul_ln1118_27_fu_409_p0;
wire  signed [9:0] mul_ln1118_27_fu_409_p1;
wire  signed [15:0] mul_ln1118_76_fu_410_p0;
wire  signed [22:0] sext_ln1118_47_fu_27751_p1;
wire  signed [6:0] mul_ln1118_76_fu_410_p1;
wire  signed [15:0] mul_ln1118_39_fu_411_p0;
wire  signed [8:0] mul_ln1118_39_fu_411_p1;
wire  signed [15:0] mul_ln1118_59_fu_412_p0;
wire   [9:0] mul_ln1118_59_fu_412_p1;
wire  signed [15:0] mul_ln1118_46_fu_413_p0;
wire   [9:0] mul_ln1118_46_fu_413_p1;
wire  signed [6:0] mul_ln1118_45_fu_414_p1;
wire  signed [15:0] mul_ln1118_53_fu_415_p0;
wire  signed [25:0] sext_ln1118_31_fu_27369_p1;
wire   [9:0] mul_ln1118_53_fu_415_p1;
wire  signed [8:0] mul_ln1118_64_fu_416_p1;
wire  signed [15:0] mul_ln1118_30_fu_417_p0;
wire   [9:0] mul_ln1118_30_fu_417_p1;
wire  signed [15:0] mul_ln1118_56_fu_418_p0;
wire   [9:0] mul_ln1118_56_fu_418_p1;
wire  signed [15:0] mul_ln1118_77_fu_419_p0;
wire  signed [8:0] mul_ln1118_77_fu_419_p1;
wire  signed [15:0] mul_ln1118_18_fu_420_p0;
wire   [9:0] mul_ln1118_18_fu_420_p1;
wire  signed [15:0] mul_ln1118_9_fu_422_p0;
wire  signed [23:0] sext_ln1118_6_fu_28175_p1;
wire   [7:0] mul_ln1118_9_fu_422_p1;
wire  signed [15:0] mul_ln1118_29_fu_423_p0;
wire  signed [9:0] mul_ln1118_29_fu_423_p1;
wire  signed [15:0] mul_ln1118_41_fu_424_p0;
wire  signed [9:0] mul_ln1118_41_fu_424_p1;
wire  signed [15:0] mul_ln1118_8_fu_425_p0;
wire   [9:0] mul_ln1118_8_fu_425_p1;
wire  signed [15:0] mul_ln708_7_fu_426_p0;
wire   [10:0] mul_ln708_7_fu_426_p1;
wire  signed [15:0] mul_ln1118_51_fu_427_p0;
wire   [9:0] mul_ln1118_51_fu_427_p1;
wire  signed [15:0] mul_ln1118_74_fu_428_p0;
wire  signed [9:0] mul_ln1118_74_fu_428_p1;
wire  signed [15:0] mul_ln1118_20_fu_429_p0;
wire  signed [9:0] mul_ln1118_20_fu_429_p1;
wire  signed [15:0] mul_ln1118_32_fu_430_p0;
wire  signed [9:0] mul_ln1118_32_fu_430_p1;
wire  signed [15:0] mul_ln1118_4_fu_431_p0;
wire   [9:0] mul_ln1118_4_fu_431_p1;
wire  signed [15:0] mul_ln1118_34_fu_433_p0;
wire  signed [9:0] mul_ln1118_34_fu_433_p1;
wire  signed [15:0] mul_ln1118_47_fu_434_p0;
wire   [9:0] mul_ln1118_47_fu_434_p1;
wire  signed [15:0] mul_ln1118_36_fu_435_p0;
wire  signed [9:0] mul_ln1118_36_fu_435_p1;
wire  signed [15:0] mul_ln1118_62_fu_436_p0;
wire  signed [9:0] mul_ln1118_62_fu_436_p1;
wire  signed [15:0] mul_ln1118_38_fu_437_p0;
wire  signed [8:0] mul_ln1118_38_fu_437_p1;
wire  signed [15:0] mul_ln1118_26_fu_439_p0;
wire  signed [6:0] mul_ln1118_26_fu_439_p1;
wire  signed [15:0] mul_ln1118_10_fu_440_p0;
wire  signed [9:0] mul_ln1118_10_fu_440_p1;
wire  signed [15:0] mul_ln1118_21_fu_442_p0;
wire   [6:0] mul_ln1118_21_fu_442_p1;
wire  signed [15:0] mul_ln1118_60_fu_443_p0;
wire   [9:0] mul_ln1118_60_fu_443_p1;
wire  signed [15:0] mul_ln1118_15_fu_444_p0;
wire  signed [9:0] mul_ln1118_15_fu_444_p1;
wire  signed [15:0] mul_ln1118_16_fu_445_p0;
wire   [9:0] mul_ln1118_16_fu_445_p1;
wire  signed [15:0] mul_ln1118_fu_446_p0;
wire   [9:0] mul_ln1118_fu_446_p1;
wire  signed [15:0] mul_ln708_4_fu_447_p0;
wire  signed [10:0] mul_ln708_4_fu_447_p1;
wire  signed [15:0] mul_ln1118_44_fu_448_p0;
wire   [9:0] mul_ln1118_44_fu_448_p1;
wire  signed [15:0] mul_ln1118_35_fu_449_p0;
wire  signed [9:0] mul_ln1118_35_fu_449_p1;
wire  signed [15:0] mul_ln1118_68_fu_450_p0;
wire   [9:0] mul_ln1118_68_fu_450_p1;
wire  signed [15:0] mul_ln1118_72_fu_451_p0;
wire   [8:0] mul_ln1118_72_fu_451_p1;
wire  signed [15:0] mul_ln1118_63_fu_452_p0;
wire   [9:0] mul_ln1118_63_fu_452_p1;
wire  signed [15:0] mul_ln1118_55_fu_453_p0;
wire  signed [9:0] mul_ln1118_55_fu_453_p1;
wire  signed [15:0] mul_ln1118_3_fu_454_p0;
wire   [9:0] mul_ln1118_3_fu_454_p1;
wire  signed [15:0] mul_ln1118_48_fu_455_p0;
wire   [7:0] mul_ln1118_48_fu_455_p1;
wire  signed [15:0] mul_ln1118_49_fu_456_p0;
wire  signed [9:0] mul_ln1118_49_fu_456_p1;
wire  signed [15:0] mul_ln1118_70_fu_457_p0;
wire   [6:0] mul_ln1118_70_fu_457_p1;
wire  signed [15:0] mul_ln1118_61_fu_463_p0;
wire   [9:0] mul_ln1118_61_fu_463_p1;
wire  signed [15:0] mul_ln708_3_fu_464_p0;
wire  signed [10:0] mul_ln708_3_fu_464_p1;
wire   [8:0] mul_ln1118_2_fu_465_p1;
wire  signed [15:0] mul_ln1118_11_fu_466_p0;
wire   [9:0] mul_ln1118_11_fu_466_p1;
wire  signed [15:0] mul_ln1118_14_fu_467_p0;
wire  signed [9:0] mul_ln1118_14_fu_467_p1;
wire  signed [15:0] mul_ln1118_52_fu_468_p0;
wire  signed [9:0] mul_ln1118_52_fu_468_p1;
wire  signed [15:0] mul_ln708_6_fu_469_p0;
wire   [10:0] mul_ln708_6_fu_469_p1;
wire  signed [15:0] mul_ln1118_6_fu_470_p0;
wire  signed [8:0] mul_ln1118_6_fu_470_p1;
wire  signed [15:0] mul_ln708_2_fu_471_p0;
wire   [10:0] mul_ln708_2_fu_471_p1;
wire  signed [15:0] mul_ln1118_73_fu_472_p0;
wire  signed [8:0] mul_ln1118_73_fu_472_p1;
wire  signed [15:0] sext_ln1118_13_fu_26635_p0;
wire   [25:0] mul_ln1118_13_fu_398_p2;
wire   [25:0] mul_ln1118_14_fu_467_p2;
wire   [25:0] mul_ln1118_15_fu_444_p2;
wire   [25:0] mul_ln1118_16_fu_445_p2;
wire   [25:0] mul_ln708_2_fu_471_p2;
wire   [25:0] mul_ln1118_17_fu_407_p2;
wire   [25:0] mul_ln1118_18_fu_420_p2;
wire  signed [15:0] shl_ln1118_5_fu_26718_p1;
wire   [23:0] shl_ln1118_5_fu_26718_p3;
wire  signed [15:0] shl_ln1118_6_fu_26730_p1;
wire   [21:0] shl_ln1118_6_fu_26730_p3;
wire  signed [24:0] sext_ln1118_14_fu_26726_p1;
wire  signed [24:0] sext_ln1118_15_fu_26738_p1;
wire   [24:0] add_ln1118_2_fu_26742_p2;
wire   [25:0] mul_ln708_3_fu_464_p2;
wire   [25:0] mul_ln1118_19_fu_379_p2;
wire  signed [15:0] sext_ln1118_16_fu_26778_p0;
wire  signed [15:0] sext_ln1118_17_fu_26785_p0;
wire   [25:0] mul_ln1118_20_fu_429_p2;
wire   [22:0] mul_ln1118_21_fu_442_p2;
wire   [25:0] mul_ln1118_22_fu_408_p2;
wire   [25:0] mul_ln1118_23_fu_389_p2;
wire   [25:0] mul_ln1118_24_fu_387_p2;
wire   [22:0] mul_ln1118_25_fu_382_p2;
wire   [22:0] mul_ln1118_26_fu_439_p2;
wire   [25:0] mul_ln1118_27_fu_409_p2;
wire   [22:0] shl_ln1118_7_fu_26877_p3;
wire   [17:0] shl_ln1118_8_fu_26889_p3;
wire  signed [23:0] sext_ln1118_18_fu_26885_p1;
wire  signed [23:0] sext_ln1118_19_fu_26897_p1;
wire   [23:0] sub_ln1118_2_fu_26901_p2;
wire   [13:0] trunc_ln708_30_fu_26907_p4;
wire   [24:0] shl_ln1118_9_fu_26924_p3;
wire   [18:0] shl_ln1118_10_fu_26936_p3;
wire  signed [25:0] sext_ln1118_20_fu_26932_p1;
wire  signed [25:0] sext_ln1118_21_fu_26944_p1;
wire   [25:0] sub_ln1118_3_fu_26948_p2;
wire  signed [15:0] sext_ln1118_24_fu_26980_p0;
wire   [25:0] mul_ln1118_28_fu_404_p2;
wire   [25:0] mul_ln1118_29_fu_423_p2;
wire   [25:0] mul_ln1118_30_fu_417_p2;
wire   [25:0] mul_ln1118_31_fu_406_p2;
wire   [25:0] mul_ln1118_32_fu_430_p2;
wire   [23:0] mul_ln1118_33_fu_374_p2;
wire   [13:0] trunc_ln708_44_fu_27042_p4;
wire   [25:0] mul_ln1118_34_fu_433_p2;
wire   [25:0] mul_ln1118_35_fu_449_p2;
wire   [25:0] mul_ln1118_36_fu_435_p2;
wire   [22:0] mul_ln1118_37_fu_384_p2;
wire   [12:0] trunc_ln708_48_fu_27086_p4;
wire  signed [15:0] sext_ln1118_26_fu_27105_p0;
wire  signed [15:0] sext_ln1118_27_fu_27114_p0;
wire   [24:0] mul_ln1118_38_fu_437_p2;
wire   [24:0] mul_ln1118_39_fu_411_p2;
wire  signed [15:0] shl_ln1118_11_fu_27141_p1;
wire   [19:0] shl_ln1118_11_fu_27141_p3;
wire  signed [20:0] sext_ln1118_28_fu_27149_p1;
wire  signed [15:0] shl_ln1118_12_fu_27159_p1;
wire   [17:0] shl_ln1118_12_fu_27159_p3;
wire   [20:0] sub_ln1118_4_fu_27153_p2;
wire  signed [20:0] sext_ln1118_29_fu_27167_p1;
wire   [20:0] sub_ln1118_5_fu_27171_p2;
wire   [24:0] mul_ln1118_40_fu_381_p2;
wire   [25:0] mul_ln1118_41_fu_424_p2;
wire   [25:0] mul_ln1118_42_fu_378_p2;
wire   [25:0] mul_ln1118_43_fu_392_p2;
wire   [25:0] mul_ln1118_44_fu_448_p2;
wire   [22:0] mul_ln1118_45_fu_414_p2;
wire   [25:0] mul_ln1118_46_fu_413_p2;
wire   [15:0] trunc_ln708_39_fu_26992_p4;
wire   [15:0] add_ln703_9_fu_27257_p2;
wire  signed [15:0] sext_ln708_8_fu_26917_p1;
wire   [15:0] trunc_ln708_40_fu_27002_p4;
wire   [15:0] add_ln703_18_fu_27267_p2;
wire  signed [15:0] sext_ln708_9_fu_26921_p1;
wire   [15:0] trunc_ln708_41_fu_27012_p4;
wire   [15:0] add_ln703_27_fu_27278_p2;
wire   [15:0] trunc_ln708_42_fu_27022_p4;
wire   [15:0] add_ln703_36_fu_27289_p2;
wire   [15:0] trunc_ln708_43_fu_27032_p4;
wire   [15:0] add_ln703_45_fu_27299_p2;
wire   [15:0] trunc_ln708_34_fu_26954_p4;
wire  signed [15:0] sext_ln708_12_fu_27052_p1;
wire   [15:0] add_ln703_54_fu_27309_p2;
wire   [15:0] trunc_ln708_45_fu_27056_p4;
wire   [15:0] add_ln703_63_fu_27320_p2;
wire  signed [15:0] sext_ln708_10_fu_26964_p1;
wire   [15:0] trunc_ln708_46_fu_27066_p4;
wire   [15:0] add_ln703_72_fu_27330_p2;
wire  signed [15:0] sext_ln708_7_fu_26874_p1;
wire  signed [15:0] sext_ln708_11_fu_26967_p1;
wire   [15:0] trunc_ln708_47_fu_27076_p4;
wire   [15:0] add_ln703_81_fu_27342_p2;
wire  signed [15:0] sext_ln708_13_fu_27096_p1;
wire   [15:0] add_ln703_90_fu_27353_p2;
wire  signed [15:0] sext_ln1118_30_fu_27363_p0;
wire  signed [15:0] sext_ln1118_31_fu_27369_p0;
wire   [25:0] mul_ln1118_47_fu_434_p2;
wire   [23:0] mul_ln1118_48_fu_455_p2;
wire   [25:0] mul_ln1118_49_fu_456_p2;
wire   [23:0] mul_ln1118_50_fu_396_p2;
wire   [25:0] mul_ln1118_51_fu_427_p2;
wire   [25:0] mul_ln1118_52_fu_468_p2;
wire   [25:0] mul_ln1118_53_fu_415_p2;
wire  signed [15:0] sext_ln1118_39_fu_27453_p0;
wire   [25:0] mul_ln1118_54_fu_395_p2;
wire   [25:0] mul_ln1118_55_fu_453_p2;
wire   [25:0] mul_ln1118_56_fu_418_p2;
wire   [25:0] mul_ln1118_57_fu_394_p2;
wire   [23:0] mul_ln1118_58_fu_388_p2;
wire   [25:0] mul_ln1118_59_fu_412_p2;
wire   [25:0] mul_ln1118_60_fu_443_p2;
wire   [25:0] mul_ln1118_61_fu_463_p2;
wire   [19:0] shl_ln1118_18_fu_27544_p3;
wire  signed [17:0] shl_ln1118_19_fu_27555_p3;
wire  signed [20:0] sext_ln1118_42_fu_27566_p1;
wire  signed [20:0] sext_ln1118_40_fu_27551_p1;
wire   [20:0] sub_ln1118_10_fu_27570_p2;
wire   [10:0] trunc_ln708_69_fu_27576_p4;
wire   [24:0] shl_ln1118_20_fu_27593_p3;
wire  signed [25:0] sext_ln1118_43_fu_27600_p1;
wire  signed [25:0] sext_ln1118_41_fu_27562_p1;
wire   [25:0] sub_ln1118_11_fu_27604_p2;
wire  signed [15:0] sext_ln1118_45_fu_27625_p0;
wire   [25:0] mul_ln708_4_fu_447_p2;
wire   [25:0] mul_ln708_5_fu_373_p2;
wire   [25:0] mul_ln708_6_fu_469_p2;
wire   [25:0] mul_ln1118_62_fu_436_p2;
wire   [25:0] mul_ln1118_63_fu_452_p2;
wire   [25:0] mul_ln708_7_fu_426_p2;
wire   [24:0] mul_ln1118_64_fu_416_p2;
wire   [14:0] trunc_ln708_85_fu_27698_p4;
wire   [25:0] mul_ln1118_65_fu_403_p2;
wire   [25:0] mul_ln1118_66_fu_402_p2;
wire   [25:0] mul_ln1118_67_fu_405_p2;
wire  signed [15:0] sext_ln1118_46_fu_27742_p0;
wire  signed [15:0] sext_ln1118_47_fu_27751_p0;
wire  signed [15:0] sext_ln1118_48_fu_27757_p0;
wire   [25:0] mul_ln1118_68_fu_450_p2;
wire   [25:0] mul_ln1118_69_fu_377_p2;
wire   [22:0] mul_ln1118_70_fu_457_p2;
wire   [12:0] trunc_ln708_91_fu_27784_p4;
wire   [24:0] mul_ln1118_71_fu_401_p2;
wire   [14:0] trunc_ln708_92_fu_27798_p4;
wire   [24:0] mul_ln1118_72_fu_451_p2;
wire   [14:0] trunc_ln708_93_fu_27812_p4;
wire   [24:0] mul_ln1118_73_fu_472_p2;
wire   [14:0] trunc_ln708_94_fu_27826_p4;
wire   [25:0] mul_ln1118_74_fu_428_p2;
wire   [24:0] mul_ln1118_75_fu_391_p2;
wire   [14:0] trunc_ln708_96_fu_27850_p4;
wire   [22:0] mul_ln1118_76_fu_410_p2;
wire   [12:0] trunc_ln708_97_fu_27864_p4;
wire   [24:0] mul_ln1118_77_fu_419_p2;
wire   [14:0] trunc_ln708_98_fu_27878_p4;
wire   [15:0] trunc_ln708_79_fu_27638_p4;
wire   [15:0] trunc_ln708_89_fu_27764_p4;
wire   [15:0] add_ln703_13_fu_27892_p2;
wire  signed [15:0] sext_ln708_24_fu_27586_p1;
wire   [15:0] trunc_ln708_80_fu_27648_p4;
wire   [15:0] trunc_ln708_90_fu_27774_p4;
wire   [15:0] add_ln703_22_fu_27904_p2;
wire   [15:0] trunc_ln708_81_fu_27658_p4;
wire  signed [15:0] sext_ln708_27_fu_27794_p1;
wire   [15:0] add_ln703_31_fu_27915_p2;
wire   [15:0] trunc_ln708_82_fu_27668_p4;
wire  signed [15:0] sext_ln708_28_fu_27808_p1;
wire   [15:0] add_ln703_40_fu_27926_p2;
wire   [15:0] trunc_ln708_83_fu_27678_p4;
wire  signed [15:0] sext_ln708_29_fu_27822_p1;
wire   [15:0] add_ln703_49_fu_27937_p2;
wire   [15:0] trunc_ln708_84_fu_27688_p4;
wire  signed [15:0] sext_ln708_30_fu_27836_p1;
wire   [15:0] add_ln703_58_fu_27948_p2;
wire  signed [15:0] sext_ln708_25_fu_27590_p1;
wire  signed [15:0] sext_ln708_26_fu_27708_p1;
wire   [15:0] trunc_ln708_95_fu_27840_p4;
wire   [15:0] add_ln703_67_fu_27960_p2;
wire   [15:0] trunc_ln708_75_fu_27610_p4;
wire   [15:0] trunc_ln708_86_fu_27712_p4;
wire  signed [15:0] sext_ln708_31_fu_27860_p1;
wire   [15:0] add_ln703_76_fu_27972_p2;
wire   [15:0] trunc_ln708_87_fu_27722_p4;
wire  signed [15:0] sext_ln708_32_fu_27874_p1;
wire   [15:0] add_ln703_85_fu_27983_p2;
wire   [15:0] trunc_ln708_88_fu_27732_p4;
wire  signed [15:0] sext_ln708_33_fu_27888_p1;
wire   [15:0] add_ln703_94_fu_27994_p2;
wire   [24:0] shl_ln_fu_28022_p3;
wire   [20:0] shl_ln1118_s_fu_28033_p3;
wire  signed [25:0] sext_ln1118_3_fu_28029_p1;
wire  signed [25:0] sext_ln1118_4_fu_28040_p1;
wire   [25:0] add_ln1118_fu_28044_p2;
wire   [18:0] shl_ln1118_1_fu_28060_p3;
wire  signed [19:0] sext_ln1118_5_fu_28067_p1;
wire  signed [19:0] sext_ln1118_1_fu_28015_p1;
wire   [19:0] sub_ln1118_fu_28071_p2;
wire   [9:0] trunc_ln708_1_fu_28077_p4;
wire   [25:0] mul_ln1118_fu_446_p2;
wire   [25:0] mul_ln1118_1_fu_385_p2;
wire   [25:0] mul_ln708_fu_375_p2;
wire   [24:0] mul_ln1118_2_fu_465_p2;
wire   [14:0] trunc_ln708_5_fu_28121_p4;
wire   [25:0] mul_ln1118_3_fu_454_p2;
wire   [25:0] mul_ln1118_4_fu_431_p2;
wire   [25:0] mul_ln1118_5_fu_399_p2;
wire   [25:0] mul_ln708_1_fu_386_p2;
wire   [24:0] mul_ln1118_6_fu_470_p2;
wire   [14:0] trunc_ln708_s_fu_28191_p4;
wire   [25:0] mul_ln1118_7_fu_380_p2;
wire   [24:0] shl_ln1118_2_fu_28215_p3;
wire  signed [16:0] shl_ln1118_3_fu_28226_p3;
wire  signed [25:0] sext_ln1118_11_fu_28237_p1;
wire  signed [25:0] sext_ln1118_9_fu_28222_p1;
wire   [25:0] sub_ln1118_1_fu_28241_p2;
wire   [25:0] mul_ln1118_8_fu_425_p2;
wire   [22:0] shl_ln1118_4_fu_28267_p3;
wire  signed [23:0] sext_ln1118_12_fu_28274_p1;
wire  signed [23:0] sext_ln1118_10_fu_28233_p1;
wire   [23:0] add_ln1118_1_fu_28278_p2;
wire   [13:0] trunc_ln708_13_fu_28284_p4;
wire   [23:0] mul_ln1118_9_fu_422_p2;
wire   [13:0] trunc_ln708_14_fu_28298_p4;
wire   [25:0] mul_ln1118_10_fu_440_p2;
wire   [25:0] mul_ln1118_11_fu_466_p2;
wire   [23:0] sub_ln1118_12_fu_28332_p2;
wire   [13:0] trunc_ln708_17_fu_28338_p4;
wire   [24:0] mul_ln1118_12_fu_390_p2;
wire   [14:0] trunc_ln708_18_fu_28352_p4;
wire   [23:0] shl_ln1118_13_fu_28384_p3;
wire   [20:0] shl_ln1118_14_fu_28396_p3;
wire  signed [24:0] sext_ln1118_32_fu_28392_p1;
wire  signed [24:0] sext_ln1118_33_fu_28404_p1;
wire   [24:0] sub_ln1118_6_fu_28408_p2;
wire   [14:0] trunc_ln708_62_fu_28414_p4;
wire   [19:0] shl_ln1118_15_fu_28428_p3;
wire  signed [20:0] sext_ln1118_34_fu_28436_p1;
wire  signed [16:0] shl_ln1118_16_fu_28446_p3;
wire   [20:0] sub_ln1118_7_fu_28440_p2;
wire  signed [20:0] sext_ln1118_36_fu_28458_p1;
wire   [20:0] sub_ln1118_8_fu_28462_p2;
wire   [10:0] trunc_ln708_63_fu_28468_p4;
wire   [21:0] shl_ln1118_17_fu_28485_p3;
wire  signed [22:0] sext_ln1118_37_fu_28493_p1;
wire  signed [22:0] sext_ln1118_35_fu_28454_p1;
wire   [22:0] sub_ln1118_9_fu_28497_p2;
wire   [12:0] trunc_ln708_68_fu_28503_p4;
wire  signed [15:0] sext_ln708_2_fu_28201_p1;
wire   [15:0] trunc_ln_fu_28050_p4;
wire   [15:0] add_ln703_fu_28517_p2;
wire  signed [15:0] sext_ln708_14_fu_28366_p1;
wire   [15:0] add_ln703_12_fu_28528_p2;
wire   [15:0] add_ln703_15_fu_28533_p2;
wire   [15:0] add_ln703_11_fu_28523_p2;
wire   [15:0] trunc_ln708_10_fu_28205_p4;
wire  signed [15:0] sext_ln708_fu_28087_p1;
wire   [15:0] add_ln703_17_fu_28544_p2;
wire  signed [15:0] sext_ln708_15_fu_28369_p1;
wire  signed [15:0] sext_ln708_19_fu_28381_p1;
wire   [15:0] add_ln703_21_fu_28555_p2;
wire   [15:0] add_ln703_24_fu_28561_p2;
wire   [15:0] add_ln703_20_fu_28550_p2;
wire   [15:0] trunc_ln708_11_fu_28247_p4;
wire   [15:0] trunc_ln708_2_fu_28091_p4;
wire   [15:0] add_ln703_26_fu_28572_p2;
wire  signed [15:0] sext_ln708_16_fu_28372_p1;
wire   [15:0] add_ln703_30_fu_28583_p2;
wire   [15:0] add_ln703_33_fu_28588_p2;
wire   [15:0] add_ln703_29_fu_28578_p2;
wire   [15:0] trunc_ln708_12_fu_28257_p4;
wire   [15:0] trunc_ln708_3_fu_28101_p4;
wire   [15:0] add_ln703_35_fu_28599_p2;
wire  signed [15:0] sext_ln708_17_fu_28375_p1;
wire  signed [15:0] sext_ln708_20_fu_28424_p1;
wire   [15:0] add_ln703_39_fu_28610_p2;
wire   [15:0] add_ln703_42_fu_28616_p2;
wire   [15:0] add_ln703_38_fu_28605_p2;
wire  signed [15:0] sext_ln708_3_fu_28294_p1;
wire   [15:0] trunc_ln708_4_fu_28111_p4;
wire   [15:0] add_ln703_44_fu_28627_p2;
wire  signed [15:0] sext_ln708_21_fu_28478_p1;
wire   [15:0] add_ln703_48_fu_28638_p2;
wire   [15:0] add_ln703_51_fu_28643_p2;
wire   [15:0] add_ln703_47_fu_28633_p2;
wire  signed [15:0] sext_ln708_4_fu_28308_p1;
wire  signed [15:0] sext_ln708_1_fu_28131_p1;
wire   [15:0] add_ln703_53_fu_28654_p2;
wire  signed [15:0] sext_ln708_22_fu_28482_p1;
wire   [15:0] add_ln703_57_fu_28665_p2;
wire   [15:0] add_ln703_60_fu_28670_p2;
wire   [15:0] add_ln703_56_fu_28660_p2;
wire   [15:0] trunc_ln708_15_fu_28312_p4;
wire   [15:0] trunc_ln708_6_fu_28135_p4;
wire   [15:0] add_ln703_62_fu_28681_p2;
wire   [15:0] add_ln703_66_fu_28692_p2;
wire   [15:0] add_ln703_69_fu_28696_p2;
wire   [15:0] add_ln703_65_fu_28687_p2;
wire   [15:0] trunc_ln708_16_fu_28322_p4;
wire   [15:0] trunc_ln708_7_fu_28145_p4;
wire   [15:0] add_ln703_71_fu_28707_p2;
wire   [15:0] add_ln703_75_fu_28718_p2;
wire   [15:0] add_ln703_78_fu_28722_p2;
wire   [15:0] add_ln703_74_fu_28713_p2;
wire  signed [15:0] sext_ln708_5_fu_28348_p1;
wire   [15:0] trunc_ln708_8_fu_28155_p4;
wire   [15:0] add_ln703_80_fu_28733_p2;
wire  signed [15:0] sext_ln708_18_fu_28378_p1;
wire   [15:0] add_ln703_84_fu_28744_p2;
wire   [15:0] add_ln703_87_fu_28749_p2;
wire   [15:0] add_ln703_83_fu_28739_p2;
wire  signed [15:0] sext_ln708_6_fu_28362_p1;
wire   [15:0] trunc_ln708_9_fu_28165_p4;
wire   [15:0] add_ln703_89_fu_28760_p2;
wire  signed [15:0] sext_ln708_23_fu_28513_p1;
wire   [15:0] add_ln703_93_fu_28771_p2;
wire   [15:0] add_ln703_96_fu_28776_p2;
wire   [15:0] add_ln703_92_fu_28766_p2;
wire   [15:0] add_ln703_16_fu_28538_p2;
wire   [15:0] add_ln703_25_fu_28566_p2;
wire   [15:0] add_ln703_34_fu_28593_p2;
wire   [15:0] add_ln703_43_fu_28621_p2;
wire   [15:0] add_ln703_52_fu_28648_p2;
wire   [15:0] add_ln703_61_fu_28675_p2;
wire   [15:0] add_ln703_70_fu_28701_p2;
wire   [15:0] add_ln703_79_fu_28727_p2;
wire   [15:0] add_ln703_88_fu_28754_p2;
wire   [15:0] add_ln703_97_fu_28781_p2;
reg   [4:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
reg    ap_idle_pp0_0to0;
reg    ap_reset_idle_pp0;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_enable_pp0;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
end

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U1(
    .din0(mul_ln708_5_fu_373_p0),
    .din1(mul_ln708_5_fu_373_p1),
    .dout(mul_ln708_5_fu_373_p2)
);

myproject_mul_16s_8s_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8s_24_1_1_U2(
    .din0(dense_input_q1),
    .din1(mul_ln1118_33_fu_374_p1),
    .dout(mul_ln1118_33_fu_374_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U3(
    .din0(mul_ln708_fu_375_p0),
    .din1(mul_ln708_fu_375_p1),
    .dout(mul_ln708_fu_375_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U4(
    .din0(mul_ln1118_69_fu_377_p0),
    .din1(mul_ln1118_69_fu_377_p1),
    .dout(mul_ln1118_69_fu_377_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U5(
    .din0(mul_ln1118_42_fu_378_p0),
    .din1(mul_ln1118_42_fu_378_p1),
    .dout(mul_ln1118_42_fu_378_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U6(
    .din0(mul_ln1118_19_fu_379_p0),
    .din1(mul_ln1118_19_fu_379_p1),
    .dout(mul_ln1118_19_fu_379_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U7(
    .din0(mul_ln1118_7_fu_380_p0),
    .din1(mul_ln1118_7_fu_380_p1),
    .dout(mul_ln1118_7_fu_380_p2)
);

myproject_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U8(
    .din0(mul_ln1118_40_fu_381_p0),
    .din1(mul_ln1118_40_fu_381_p1),
    .dout(mul_ln1118_40_fu_381_p2)
);

myproject_mul_16s_7ns_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7ns_23_1_1_U9(
    .din0(mul_ln1118_25_fu_382_p0),
    .din1(mul_ln1118_25_fu_382_p1),
    .dout(mul_ln1118_25_fu_382_p2)
);

myproject_mul_16s_7s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7s_23_1_1_U10(
    .din0(dense_input_q1),
    .din1(mul_ln1118_37_fu_384_p1),
    .dout(mul_ln1118_37_fu_384_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U11(
    .din0(mul_ln1118_1_fu_385_p0),
    .din1(mul_ln1118_1_fu_385_p1),
    .dout(mul_ln1118_1_fu_385_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U12(
    .din0(mul_ln708_1_fu_386_p0),
    .din1(mul_ln708_1_fu_386_p1),
    .dout(mul_ln708_1_fu_386_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U13(
    .din0(mul_ln1118_24_fu_387_p0),
    .din1(mul_ln1118_24_fu_387_p1),
    .dout(mul_ln1118_24_fu_387_p2)
);

myproject_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U14(
    .din0(dense_input_q0),
    .din1(mul_ln1118_58_fu_388_p1),
    .dout(mul_ln1118_58_fu_388_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U15(
    .din0(mul_ln1118_23_fu_389_p0),
    .din1(mul_ln1118_23_fu_389_p1),
    .dout(mul_ln1118_23_fu_389_p2)
);

myproject_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U16(
    .din0(mul_ln1118_12_fu_390_p0),
    .din1(mul_ln1118_12_fu_390_p1),
    .dout(mul_ln1118_12_fu_390_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U17(
    .din0(mul_ln1118_75_fu_391_p0),
    .din1(mul_ln1118_75_fu_391_p1),
    .dout(mul_ln1118_75_fu_391_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U18(
    .din0(mul_ln1118_43_fu_392_p0),
    .din1(mul_ln1118_43_fu_392_p1),
    .dout(mul_ln1118_43_fu_392_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U19(
    .din0(mul_ln1118_57_fu_394_p0),
    .din1(mul_ln1118_57_fu_394_p1),
    .dout(mul_ln1118_57_fu_394_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U20(
    .din0(mul_ln1118_54_fu_395_p0),
    .din1(mul_ln1118_54_fu_395_p1),
    .dout(mul_ln1118_54_fu_395_p2)
);

myproject_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U21(
    .din0(mul_ln1118_50_fu_396_p0),
    .din1(mul_ln1118_50_fu_396_p1),
    .dout(mul_ln1118_50_fu_396_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U22(
    .din0(mul_ln1118_13_fu_398_p0),
    .din1(mul_ln1118_13_fu_398_p1),
    .dout(mul_ln1118_13_fu_398_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U23(
    .din0(mul_ln1118_5_fu_399_p0),
    .din1(mul_ln1118_5_fu_399_p1),
    .dout(mul_ln1118_5_fu_399_p2)
);

myproject_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U24(
    .din0(mul_ln1118_71_fu_401_p0),
    .din1(mul_ln1118_71_fu_401_p1),
    .dout(mul_ln1118_71_fu_401_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U25(
    .din0(mul_ln1118_66_fu_402_p0),
    .din1(mul_ln1118_66_fu_402_p1),
    .dout(mul_ln1118_66_fu_402_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U26(
    .din0(mul_ln1118_65_fu_403_p0),
    .din1(mul_ln1118_65_fu_403_p1),
    .dout(mul_ln1118_65_fu_403_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U27(
    .din0(mul_ln1118_28_fu_404_p0),
    .din1(mul_ln1118_28_fu_404_p1),
    .dout(mul_ln1118_28_fu_404_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U28(
    .din0(mul_ln1118_67_fu_405_p0),
    .din1(mul_ln1118_67_fu_405_p1),
    .dout(mul_ln1118_67_fu_405_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U29(
    .din0(mul_ln1118_31_fu_406_p0),
    .din1(mul_ln1118_31_fu_406_p1),
    .dout(mul_ln1118_31_fu_406_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U30(
    .din0(mul_ln1118_17_fu_407_p0),
    .din1(mul_ln1118_17_fu_407_p1),
    .dout(mul_ln1118_17_fu_407_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U31(
    .din0(mul_ln1118_22_fu_408_p0),
    .din1(mul_ln1118_22_fu_408_p1),
    .dout(mul_ln1118_22_fu_408_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U32(
    .din0(mul_ln1118_27_fu_409_p0),
    .din1(mul_ln1118_27_fu_409_p1),
    .dout(mul_ln1118_27_fu_409_p2)
);

myproject_mul_16s_7s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7s_23_1_1_U33(
    .din0(mul_ln1118_76_fu_410_p0),
    .din1(mul_ln1118_76_fu_410_p1),
    .dout(mul_ln1118_76_fu_410_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U34(
    .din0(mul_ln1118_39_fu_411_p0),
    .din1(mul_ln1118_39_fu_411_p1),
    .dout(mul_ln1118_39_fu_411_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U35(
    .din0(mul_ln1118_59_fu_412_p0),
    .din1(mul_ln1118_59_fu_412_p1),
    .dout(mul_ln1118_59_fu_412_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U36(
    .din0(mul_ln1118_46_fu_413_p0),
    .din1(mul_ln1118_46_fu_413_p1),
    .dout(mul_ln1118_46_fu_413_p2)
);

myproject_mul_16s_7s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7s_23_1_1_U37(
    .din0(dense_input_q0),
    .din1(mul_ln1118_45_fu_414_p1),
    .dout(mul_ln1118_45_fu_414_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U38(
    .din0(mul_ln1118_53_fu_415_p0),
    .din1(mul_ln1118_53_fu_415_p1),
    .dout(mul_ln1118_53_fu_415_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U39(
    .din0(dense_input_q1),
    .din1(mul_ln1118_64_fu_416_p1),
    .dout(mul_ln1118_64_fu_416_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U40(
    .din0(mul_ln1118_30_fu_417_p0),
    .din1(mul_ln1118_30_fu_417_p1),
    .dout(mul_ln1118_30_fu_417_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U41(
    .din0(mul_ln1118_56_fu_418_p0),
    .din1(mul_ln1118_56_fu_418_p1),
    .dout(mul_ln1118_56_fu_418_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U42(
    .din0(mul_ln1118_77_fu_419_p0),
    .din1(mul_ln1118_77_fu_419_p1),
    .dout(mul_ln1118_77_fu_419_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U43(
    .din0(mul_ln1118_18_fu_420_p0),
    .din1(mul_ln1118_18_fu_420_p1),
    .dout(mul_ln1118_18_fu_420_p2)
);

myproject_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U44(
    .din0(mul_ln1118_9_fu_422_p0),
    .din1(mul_ln1118_9_fu_422_p1),
    .dout(mul_ln1118_9_fu_422_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U45(
    .din0(mul_ln1118_29_fu_423_p0),
    .din1(mul_ln1118_29_fu_423_p1),
    .dout(mul_ln1118_29_fu_423_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U46(
    .din0(mul_ln1118_41_fu_424_p0),
    .din1(mul_ln1118_41_fu_424_p1),
    .dout(mul_ln1118_41_fu_424_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U47(
    .din0(mul_ln1118_8_fu_425_p0),
    .din1(mul_ln1118_8_fu_425_p1),
    .dout(mul_ln1118_8_fu_425_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U48(
    .din0(mul_ln708_7_fu_426_p0),
    .din1(mul_ln708_7_fu_426_p1),
    .dout(mul_ln708_7_fu_426_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U49(
    .din0(mul_ln1118_51_fu_427_p0),
    .din1(mul_ln1118_51_fu_427_p1),
    .dout(mul_ln1118_51_fu_427_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U50(
    .din0(mul_ln1118_74_fu_428_p0),
    .din1(mul_ln1118_74_fu_428_p1),
    .dout(mul_ln1118_74_fu_428_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U51(
    .din0(mul_ln1118_20_fu_429_p0),
    .din1(mul_ln1118_20_fu_429_p1),
    .dout(mul_ln1118_20_fu_429_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U52(
    .din0(mul_ln1118_32_fu_430_p0),
    .din1(mul_ln1118_32_fu_430_p1),
    .dout(mul_ln1118_32_fu_430_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U53(
    .din0(mul_ln1118_4_fu_431_p0),
    .din1(mul_ln1118_4_fu_431_p1),
    .dout(mul_ln1118_4_fu_431_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U54(
    .din0(mul_ln1118_34_fu_433_p0),
    .din1(mul_ln1118_34_fu_433_p1),
    .dout(mul_ln1118_34_fu_433_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U55(
    .din0(mul_ln1118_47_fu_434_p0),
    .din1(mul_ln1118_47_fu_434_p1),
    .dout(mul_ln1118_47_fu_434_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U56(
    .din0(mul_ln1118_36_fu_435_p0),
    .din1(mul_ln1118_36_fu_435_p1),
    .dout(mul_ln1118_36_fu_435_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U57(
    .din0(mul_ln1118_62_fu_436_p0),
    .din1(mul_ln1118_62_fu_436_p1),
    .dout(mul_ln1118_62_fu_436_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U58(
    .din0(mul_ln1118_38_fu_437_p0),
    .din1(mul_ln1118_38_fu_437_p1),
    .dout(mul_ln1118_38_fu_437_p2)
);

myproject_mul_16s_7s_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7s_23_1_1_U59(
    .din0(mul_ln1118_26_fu_439_p0),
    .din1(mul_ln1118_26_fu_439_p1),
    .dout(mul_ln1118_26_fu_439_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U60(
    .din0(mul_ln1118_10_fu_440_p0),
    .din1(mul_ln1118_10_fu_440_p1),
    .dout(mul_ln1118_10_fu_440_p2)
);

myproject_mul_16s_7ns_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7ns_23_1_1_U61(
    .din0(mul_ln1118_21_fu_442_p0),
    .din1(mul_ln1118_21_fu_442_p1),
    .dout(mul_ln1118_21_fu_442_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U62(
    .din0(mul_ln1118_60_fu_443_p0),
    .din1(mul_ln1118_60_fu_443_p1),
    .dout(mul_ln1118_60_fu_443_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U63(
    .din0(mul_ln1118_15_fu_444_p0),
    .din1(mul_ln1118_15_fu_444_p1),
    .dout(mul_ln1118_15_fu_444_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U64(
    .din0(mul_ln1118_16_fu_445_p0),
    .din1(mul_ln1118_16_fu_445_p1),
    .dout(mul_ln1118_16_fu_445_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U65(
    .din0(mul_ln1118_fu_446_p0),
    .din1(mul_ln1118_fu_446_p1),
    .dout(mul_ln1118_fu_446_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U66(
    .din0(mul_ln708_4_fu_447_p0),
    .din1(mul_ln708_4_fu_447_p1),
    .dout(mul_ln708_4_fu_447_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U67(
    .din0(mul_ln1118_44_fu_448_p0),
    .din1(mul_ln1118_44_fu_448_p1),
    .dout(mul_ln1118_44_fu_448_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U68(
    .din0(mul_ln1118_35_fu_449_p0),
    .din1(mul_ln1118_35_fu_449_p1),
    .dout(mul_ln1118_35_fu_449_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U69(
    .din0(mul_ln1118_68_fu_450_p0),
    .din1(mul_ln1118_68_fu_450_p1),
    .dout(mul_ln1118_68_fu_450_p2)
);

myproject_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U70(
    .din0(mul_ln1118_72_fu_451_p0),
    .din1(mul_ln1118_72_fu_451_p1),
    .dout(mul_ln1118_72_fu_451_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U71(
    .din0(mul_ln1118_63_fu_452_p0),
    .din1(mul_ln1118_63_fu_452_p1),
    .dout(mul_ln1118_63_fu_452_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U72(
    .din0(mul_ln1118_55_fu_453_p0),
    .din1(mul_ln1118_55_fu_453_p1),
    .dout(mul_ln1118_55_fu_453_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U73(
    .din0(mul_ln1118_3_fu_454_p0),
    .din1(mul_ln1118_3_fu_454_p1),
    .dout(mul_ln1118_3_fu_454_p2)
);

myproject_mul_16s_8ns_24_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 8 ),
    .dout_WIDTH( 24 ))
mul_16s_8ns_24_1_1_U74(
    .din0(mul_ln1118_48_fu_455_p0),
    .din1(mul_ln1118_48_fu_455_p1),
    .dout(mul_ln1118_48_fu_455_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U75(
    .din0(mul_ln1118_49_fu_456_p0),
    .din1(mul_ln1118_49_fu_456_p1),
    .dout(mul_ln1118_49_fu_456_p2)
);

myproject_mul_16s_7ns_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 7 ),
    .dout_WIDTH( 23 ))
mul_16s_7ns_23_1_1_U76(
    .din0(mul_ln1118_70_fu_457_p0),
    .din1(mul_ln1118_70_fu_457_p1),
    .dout(mul_ln1118_70_fu_457_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U77(
    .din0(mul_ln1118_61_fu_463_p0),
    .din1(mul_ln1118_61_fu_463_p1),
    .dout(mul_ln1118_61_fu_463_p2)
);

myproject_mul_16s_11s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11s_26_1_1_U78(
    .din0(mul_ln708_3_fu_464_p0),
    .din1(mul_ln708_3_fu_464_p1),
    .dout(mul_ln708_3_fu_464_p2)
);

myproject_mul_16s_9ns_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9ns_25_1_1_U79(
    .din0(dense_input_load_reg_28857),
    .din1(mul_ln1118_2_fu_465_p1),
    .dout(mul_ln1118_2_fu_465_p2)
);

myproject_mul_16s_10ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10ns_26_1_1_U80(
    .din0(mul_ln1118_11_fu_466_p0),
    .din1(mul_ln1118_11_fu_466_p1),
    .dout(mul_ln1118_11_fu_466_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U81(
    .din0(mul_ln1118_14_fu_467_p0),
    .din1(mul_ln1118_14_fu_467_p1),
    .dout(mul_ln1118_14_fu_467_p2)
);

myproject_mul_16s_10s_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 10 ),
    .dout_WIDTH( 26 ))
mul_16s_10s_26_1_1_U82(
    .din0(mul_ln1118_52_fu_468_p0),
    .din1(mul_ln1118_52_fu_468_p1),
    .dout(mul_ln1118_52_fu_468_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U83(
    .din0(mul_ln708_6_fu_469_p0),
    .din1(mul_ln708_6_fu_469_p1),
    .dout(mul_ln708_6_fu_469_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U84(
    .din0(mul_ln1118_6_fu_470_p0),
    .din1(mul_ln1118_6_fu_470_p1),
    .dout(mul_ln1118_6_fu_470_p2)
);

myproject_mul_16s_11ns_26_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 26 ))
mul_16s_11ns_26_1_1_U85(
    .din0(mul_ln708_2_fu_471_p0),
    .din1(mul_ln708_2_fu_471_p1),
    .dout(mul_ln708_2_fu_471_p2)
);

myproject_mul_16s_9s_25_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 9 ),
    .dout_WIDTH( 25 ))
mul_16s_9s_25_1_1_U86(
    .din0(mul_ln1118_73_fu_472_p0),
    .din1(mul_ln1118_73_fu_472_p1),
    .dout(mul_ln1118_73_fu_472_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if (((1'b0 == ap_block_pp0_stage4_subdone) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_enable_reg_pp0_iter0 == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            reg_26630 <= dense_input_q1;
        end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            reg_26630 <= dense_input_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        add_ln703_10_reg_29047 <= add_ln703_10_fu_27262_p2;
        add_ln703_19_reg_29052 <= add_ln703_19_fu_27273_p2;
        add_ln703_28_reg_29057 <= add_ln703_28_fu_27284_p2;
        add_ln703_37_reg_29062 <= add_ln703_37_fu_27294_p2;
        add_ln703_46_reg_29067 <= add_ln703_46_fu_27304_p2;
        add_ln703_55_reg_29072 <= add_ln703_55_fu_27315_p2;
        add_ln703_64_reg_29077 <= add_ln703_64_fu_27325_p2;
        add_ln703_73_reg_29082 <= add_ln703_73_fu_27336_p2;
        add_ln703_82_reg_29087 <= add_ln703_82_fu_27348_p2;
        add_ln703_91_reg_29092 <= add_ln703_91_fu_27358_p2;
        trunc_ln708_49_reg_28987 <= {{mul_ln1118_38_fu_437_p2[24:10]}};
        trunc_ln708_50_reg_28992 <= {{mul_ln1118_39_fu_411_p2[24:10]}};
        trunc_ln708_51_reg_28997 <= {{sub_ln1118_5_fu_27171_p2[20:10]}};
        trunc_ln708_52_reg_29002 <= {{mul_ln1118_40_fu_381_p2[24:10]}};
        trunc_ln708_53_reg_29007 <= {{mul_ln1118_41_fu_424_p2[25:10]}};
        trunc_ln708_54_reg_29012 <= {{mul_ln1118_42_fu_378_p2[25:10]}};
        trunc_ln708_55_reg_29017 <= {{mul_ln1118_43_fu_392_p2[25:10]}};
        trunc_ln708_56_reg_29022 <= {{mul_ln1118_44_fu_448_p2[25:10]}};
        trunc_ln708_57_reg_29027 <= {{mul_ln1118_45_fu_414_p2[22:10]}};
        trunc_ln708_58_reg_29032 <= {{mul_ln1118_46_fu_413_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln703_14_reg_29189 <= add_ln703_14_fu_27898_p2;
        add_ln703_23_reg_29194 <= add_ln703_23_fu_27910_p2;
        add_ln703_32_reg_29199 <= add_ln703_32_fu_27921_p2;
        add_ln703_41_reg_29204 <= add_ln703_41_fu_27932_p2;
        add_ln703_50_reg_29209 <= add_ln703_50_fu_27943_p2;
        add_ln703_59_reg_29214 <= add_ln703_59_fu_27954_p2;
        add_ln703_68_reg_29219 <= add_ln703_68_fu_27966_p2;
        add_ln703_77_reg_29224 <= add_ln703_77_fu_27978_p2;
        add_ln703_86_reg_29229 <= add_ln703_86_fu_27989_p2;
        add_ln703_95_reg_29234 <= add_ln703_95_fu_28000_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        dense_input_load_1_reg_28867 <= dense_input_q0;
        dense_input_load_reg_28857 <= dense_input_q1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        dense_input_load_7_reg_29132 <= dense_input_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        trunc_ln708_19_reg_28887 <= {{mul_ln1118_13_fu_398_p2[25:10]}};
        trunc_ln708_20_reg_28892 <= {{mul_ln1118_14_fu_467_p2[25:10]}};
        trunc_ln708_21_reg_28897 <= {{mul_ln1118_15_fu_444_p2[25:10]}};
        trunc_ln708_22_reg_28902 <= {{mul_ln1118_16_fu_445_p2[25:10]}};
        trunc_ln708_23_reg_28907 <= {{mul_ln708_2_fu_471_p2[25:10]}};
        trunc_ln708_24_reg_28912 <= {{mul_ln1118_17_fu_407_p2[25:10]}};
        trunc_ln708_25_reg_28917 <= {{mul_ln1118_18_fu_420_p2[25:10]}};
        trunc_ln708_26_reg_28922 <= {{add_ln1118_2_fu_26742_p2[24:10]}};
        trunc_ln708_27_reg_28927 <= {{mul_ln708_3_fu_464_p2[25:10]}};
        trunc_ln708_28_reg_28932 <= {{mul_ln1118_19_fu_379_p2[25:10]}};
        trunc_ln708_29_reg_28937 <= {{mul_ln1118_20_fu_429_p2[25:10]}};
        trunc_ln708_31_reg_28942 <= {{mul_ln1118_21_fu_442_p2[22:10]}};
        trunc_ln708_32_reg_28947 <= {{mul_ln1118_22_fu_408_p2[25:10]}};
        trunc_ln708_33_reg_28952 <= {{mul_ln1118_23_fu_389_p2[25:10]}};
        trunc_ln708_35_reg_28957 <= {{mul_ln1118_24_fu_387_p2[25:10]}};
        trunc_ln708_36_reg_28962 <= {{mul_ln1118_25_fu_382_p2[22:10]}};
        trunc_ln708_37_reg_28967 <= {{mul_ln1118_26_fu_439_p2[22:10]}};
        trunc_ln708_38_reg_28972 <= {{mul_ln1118_27_fu_409_p2[25:10]}};
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        trunc_ln708_59_reg_29097 <= {{mul_ln1118_47_fu_434_p2[25:10]}};
        trunc_ln708_60_reg_29102 <= {{mul_ln1118_48_fu_455_p2[23:10]}};
        trunc_ln708_61_reg_29107 <= {{mul_ln1118_49_fu_456_p2[25:10]}};
        trunc_ln708_64_reg_29112 <= {{mul_ln1118_50_fu_396_p2[23:10]}};
        trunc_ln708_65_reg_29117 <= {{mul_ln1118_51_fu_427_p2[25:10]}};
        trunc_ln708_66_reg_29122 <= {{mul_ln1118_52_fu_468_p2[25:10]}};
        trunc_ln708_67_reg_29127 <= {{mul_ln1118_53_fu_415_p2[25:10]}};
        trunc_ln708_70_reg_29139 <= {{mul_ln1118_54_fu_395_p2[25:10]}};
        trunc_ln708_71_reg_29144 <= {{mul_ln1118_55_fu_453_p2[25:10]}};
        trunc_ln708_72_reg_29149 <= {{mul_ln1118_56_fu_418_p2[25:10]}};
        trunc_ln708_73_reg_29154 <= {{mul_ln1118_57_fu_394_p2[25:10]}};
        trunc_ln708_74_reg_29159 <= {{mul_ln1118_58_fu_388_p2[23:10]}};
        trunc_ln708_76_reg_29164 <= {{mul_ln1118_59_fu_412_p2[25:10]}};
        trunc_ln708_77_reg_29169 <= {{mul_ln1118_60_fu_443_p2[25:10]}};
        trunc_ln708_78_reg_29174 <= {{mul_ln1118_61_fu_463_p2[25:10]}};
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter1 == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b0)) begin
        ap_idle_pp0_0to0 = 1'b1;
    end else begin
        ap_idle_pp0_0to0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if (((ap_idle_pp0_0to0 == 1'b1) & (ap_start == 1'b0))) begin
        ap_reset_idle_pp0 = 1'b1;
    end else begin
        ap_reset_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            dense_input_address0 = 64'd9;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            dense_input_address0 = 64'd7;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            dense_input_address0 = 64'd5;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            dense_input_address0 = 64'd3;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dense_input_address0 = 64'd1;
        end else begin
            dense_input_address0 = 'bx;
        end
    end else begin
        dense_input_address0 = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0 == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            dense_input_address1 = 64'd8;
        end else if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            dense_input_address1 = 64'd6;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            dense_input_address1 = 64'd4;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            dense_input_address1 = 64'd2;
        end else if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            dense_input_address1 = 64'd0;
        end else begin
            dense_input_address1 = 'bx;
        end
    end else begin
        dense_input_address1 = 'bx;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        dense_input_ce0 = 1'b1;
    end else begin
        dense_input_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)) | ((1'b0 == ap_block_pp0_stage2_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((1'b0 == ap_block_pp0_stage4_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((1'b0 == ap_block_pp0_stage3_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)))) begin
        dense_input_ce1 = 1'b1;
    end else begin
        dense_input_ce1 = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_idle_pp0_1to1 == 1'b1) & (ap_start == 1'b0)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_reset_idle_pp0 == 1'b0))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else if (((1'b0 == ap_block_pp0_stage1_subdone) & (ap_reset_idle_pp0 == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln1118_1_fu_28278_p2 = ($signed(sext_ln1118_12_fu_28274_p1) + $signed(sext_ln1118_10_fu_28233_p1));

assign add_ln1118_2_fu_26742_p2 = ($signed(sext_ln1118_14_fu_26726_p1) + $signed(sext_ln1118_15_fu_26738_p1));

assign add_ln1118_fu_28044_p2 = ($signed(sext_ln1118_3_fu_28029_p1) + $signed(sext_ln1118_4_fu_28040_p1));

assign add_ln703_10_fu_27262_p2 = (add_ln703_9_fu_27257_p2 + trunc_ln708_19_reg_28887);

assign add_ln703_11_fu_28523_p2 = (add_ln703_10_reg_29047 + add_ln703_fu_28517_p2);

assign add_ln703_12_fu_28528_p2 = ($signed(sext_ln708_14_fu_28366_p1) + $signed(trunc_ln708_59_reg_29097));

assign add_ln703_13_fu_27892_p2 = (trunc_ln708_79_fu_27638_p4 + trunc_ln708_89_fu_27764_p4);

assign add_ln703_14_fu_27898_p2 = ($signed(add_ln703_13_fu_27892_p2) + $signed(sext_ln708_24_fu_27586_p1));

assign add_ln703_15_fu_28533_p2 = (add_ln703_14_reg_29189 + add_ln703_12_fu_28528_p2);

assign add_ln703_16_fu_28538_p2 = (add_ln703_15_fu_28533_p2 + add_ln703_11_fu_28523_p2);

assign add_ln703_17_fu_28544_p2 = ($signed(trunc_ln708_10_fu_28205_p4) + $signed(sext_ln708_fu_28087_p1));

assign add_ln703_18_fu_27267_p2 = ($signed(sext_ln708_8_fu_26917_p1) + $signed(trunc_ln708_40_fu_27002_p4));

assign add_ln703_19_fu_27273_p2 = (add_ln703_18_fu_27267_p2 + trunc_ln708_20_reg_28892);

assign add_ln703_20_fu_28550_p2 = (add_ln703_19_reg_29052 + add_ln703_17_fu_28544_p2);

assign add_ln703_21_fu_28555_p2 = ($signed(sext_ln708_15_fu_28369_p1) + $signed(sext_ln708_19_fu_28381_p1));

assign add_ln703_22_fu_27904_p2 = (trunc_ln708_80_fu_27648_p4 + trunc_ln708_90_fu_27774_p4);

assign add_ln703_23_fu_27910_p2 = (add_ln703_22_fu_27904_p2 + trunc_ln708_70_reg_29139);

assign add_ln703_24_fu_28561_p2 = (add_ln703_23_reg_29194 + add_ln703_21_fu_28555_p2);

assign add_ln703_25_fu_28566_p2 = (add_ln703_24_fu_28561_p2 + add_ln703_20_fu_28550_p2);

assign add_ln703_26_fu_28572_p2 = (trunc_ln708_11_fu_28247_p4 + trunc_ln708_2_fu_28091_p4);

assign add_ln703_27_fu_27278_p2 = ($signed(sext_ln708_9_fu_26921_p1) + $signed(trunc_ln708_41_fu_27012_p4));

assign add_ln703_28_fu_27284_p2 = (add_ln703_27_fu_27278_p2 + trunc_ln708_21_reg_28897);

assign add_ln703_29_fu_28578_p2 = (add_ln703_28_reg_29057 + add_ln703_26_fu_28572_p2);

assign add_ln703_30_fu_28583_p2 = ($signed(sext_ln708_16_fu_28372_p1) + $signed(trunc_ln708_61_reg_29107));

assign add_ln703_31_fu_27915_p2 = ($signed(trunc_ln708_81_fu_27658_p4) + $signed(sext_ln708_27_fu_27794_p1));

assign add_ln703_32_fu_27921_p2 = (add_ln703_31_fu_27915_p2 + trunc_ln708_71_reg_29144);

assign add_ln703_33_fu_28588_p2 = (add_ln703_32_reg_29199 + add_ln703_30_fu_28583_p2);

assign add_ln703_34_fu_28593_p2 = (add_ln703_33_fu_28588_p2 + add_ln703_29_fu_28578_p2);

assign add_ln703_35_fu_28599_p2 = (trunc_ln708_12_fu_28257_p4 + trunc_ln708_3_fu_28101_p4);

assign add_ln703_36_fu_27289_p2 = (trunc_ln708_32_reg_28947 + trunc_ln708_42_fu_27022_p4);

assign add_ln703_37_fu_27294_p2 = (add_ln703_36_fu_27289_p2 + trunc_ln708_22_reg_28902);

assign add_ln703_38_fu_28605_p2 = (add_ln703_37_reg_29062 + add_ln703_35_fu_28599_p2);

assign add_ln703_39_fu_28610_p2 = ($signed(sext_ln708_17_fu_28375_p1) + $signed(sext_ln708_20_fu_28424_p1));

assign add_ln703_40_fu_27926_p2 = ($signed(trunc_ln708_82_fu_27668_p4) + $signed(sext_ln708_28_fu_27808_p1));

assign add_ln703_41_fu_27932_p2 = (add_ln703_40_fu_27926_p2 + trunc_ln708_72_reg_29149);

assign add_ln703_42_fu_28616_p2 = (add_ln703_41_reg_29204 + add_ln703_39_fu_28610_p2);

assign add_ln703_43_fu_28621_p2 = (add_ln703_42_fu_28616_p2 + add_ln703_38_fu_28605_p2);

assign add_ln703_44_fu_28627_p2 = ($signed(sext_ln708_3_fu_28294_p1) + $signed(trunc_ln708_4_fu_28111_p4));

assign add_ln703_45_fu_27299_p2 = (trunc_ln708_33_reg_28952 + trunc_ln708_43_fu_27032_p4);

assign add_ln703_46_fu_27304_p2 = (add_ln703_45_fu_27299_p2 + trunc_ln708_23_reg_28907);

assign add_ln703_47_fu_28633_p2 = (add_ln703_46_reg_29067 + add_ln703_44_fu_28627_p2);

assign add_ln703_48_fu_28638_p2 = ($signed(trunc_ln708_53_reg_29007) + $signed(sext_ln708_21_fu_28478_p1));

assign add_ln703_49_fu_27937_p2 = ($signed(trunc_ln708_83_fu_27678_p4) + $signed(sext_ln708_29_fu_27822_p1));

assign add_ln703_50_fu_27943_p2 = (add_ln703_49_fu_27937_p2 + trunc_ln708_73_reg_29154);

assign add_ln703_51_fu_28643_p2 = (add_ln703_50_reg_29209 + add_ln703_48_fu_28638_p2);

assign add_ln703_52_fu_28648_p2 = (add_ln703_51_fu_28643_p2 + add_ln703_47_fu_28633_p2);

assign add_ln703_53_fu_28654_p2 = ($signed(sext_ln708_4_fu_28308_p1) + $signed(sext_ln708_1_fu_28131_p1));

assign add_ln703_54_fu_27309_p2 = ($signed(trunc_ln708_34_fu_26954_p4) + $signed(sext_ln708_12_fu_27052_p1));

assign add_ln703_55_fu_27315_p2 = (add_ln703_54_fu_27309_p2 + trunc_ln708_24_reg_28912);

assign add_ln703_56_fu_28660_p2 = (add_ln703_55_reg_29072 + add_ln703_53_fu_28654_p2);

assign add_ln703_57_fu_28665_p2 = ($signed(trunc_ln708_54_reg_29012) + $signed(sext_ln708_22_fu_28482_p1));

assign add_ln703_58_fu_27948_p2 = ($signed(trunc_ln708_84_fu_27688_p4) + $signed(sext_ln708_30_fu_27836_p1));

assign add_ln703_59_fu_27954_p2 = ($signed(add_ln703_58_fu_27948_p2) + $signed(sext_ln708_25_fu_27590_p1));

assign add_ln703_60_fu_28670_p2 = (add_ln703_59_reg_29214 + add_ln703_57_fu_28665_p2);

assign add_ln703_61_fu_28675_p2 = (add_ln703_60_fu_28670_p2 + add_ln703_56_fu_28660_p2);

assign add_ln703_62_fu_28681_p2 = (trunc_ln708_15_fu_28312_p4 + trunc_ln708_6_fu_28135_p4);

assign add_ln703_63_fu_27320_p2 = (trunc_ln708_35_reg_28957 + trunc_ln708_45_fu_27056_p4);

assign add_ln703_64_fu_27325_p2 = (add_ln703_63_fu_27320_p2 + trunc_ln708_25_reg_28917);

assign add_ln703_65_fu_28687_p2 = (add_ln703_64_reg_29077 + add_ln703_62_fu_28681_p2);

assign add_ln703_66_fu_28692_p2 = (trunc_ln708_55_reg_29017 + trunc_ln708_65_reg_29117);

assign add_ln703_67_fu_27960_p2 = ($signed(sext_ln708_26_fu_27708_p1) + $signed(trunc_ln708_95_fu_27840_p4));

assign add_ln703_68_fu_27966_p2 = (add_ln703_67_fu_27960_p2 + trunc_ln708_75_fu_27610_p4);

assign add_ln703_69_fu_28696_p2 = (add_ln703_68_reg_29219 + add_ln703_66_fu_28692_p2);

assign add_ln703_70_fu_28701_p2 = (add_ln703_69_fu_28696_p2 + add_ln703_65_fu_28687_p2);

assign add_ln703_71_fu_28707_p2 = (trunc_ln708_16_fu_28322_p4 + trunc_ln708_7_fu_28145_p4);

assign add_ln703_72_fu_27330_p2 = ($signed(sext_ln708_10_fu_26964_p1) + $signed(trunc_ln708_46_fu_27066_p4));

assign add_ln703_73_fu_27336_p2 = ($signed(add_ln703_72_fu_27330_p2) + $signed(sext_ln708_7_fu_26874_p1));

assign add_ln703_74_fu_28713_p2 = (add_ln703_73_reg_29082 + add_ln703_71_fu_28707_p2);

assign add_ln703_75_fu_28718_p2 = (trunc_ln708_56_reg_29022 + trunc_ln708_66_reg_29122);

assign add_ln703_76_fu_27972_p2 = ($signed(trunc_ln708_86_fu_27712_p4) + $signed(sext_ln708_31_fu_27860_p1));

assign add_ln703_77_fu_27978_p2 = (add_ln703_76_fu_27972_p2 + trunc_ln708_76_reg_29164);

assign add_ln703_78_fu_28722_p2 = (add_ln703_77_reg_29224 + add_ln703_75_fu_28718_p2);

assign add_ln703_79_fu_28727_p2 = (add_ln703_78_fu_28722_p2 + add_ln703_74_fu_28713_p2);

assign add_ln703_80_fu_28733_p2 = ($signed(sext_ln708_5_fu_28348_p1) + $signed(trunc_ln708_8_fu_28155_p4));

assign add_ln703_81_fu_27342_p2 = ($signed(sext_ln708_11_fu_26967_p1) + $signed(trunc_ln708_47_fu_27076_p4));

assign add_ln703_82_fu_27348_p2 = (add_ln703_81_fu_27342_p2 + trunc_ln708_27_reg_28927);

assign add_ln703_83_fu_28739_p2 = (add_ln703_82_reg_29087 + add_ln703_80_fu_28733_p2);

assign add_ln703_84_fu_28744_p2 = ($signed(sext_ln708_18_fu_28378_p1) + $signed(trunc_ln708_67_reg_29127));

assign add_ln703_85_fu_27983_p2 = ($signed(trunc_ln708_87_fu_27722_p4) + $signed(sext_ln708_32_fu_27874_p1));

assign add_ln703_86_fu_27989_p2 = (add_ln703_85_fu_27983_p2 + trunc_ln708_77_reg_29169);

assign add_ln703_87_fu_28749_p2 = (add_ln703_86_reg_29229 + add_ln703_84_fu_28744_p2);

assign add_ln703_88_fu_28754_p2 = (add_ln703_87_fu_28749_p2 + add_ln703_83_fu_28739_p2);

assign add_ln703_89_fu_28760_p2 = ($signed(sext_ln708_6_fu_28362_p1) + $signed(trunc_ln708_9_fu_28165_p4));

assign add_ln703_90_fu_27353_p2 = ($signed(trunc_ln708_38_reg_28972) + $signed(sext_ln708_13_fu_27096_p1));

assign add_ln703_91_fu_27358_p2 = (add_ln703_90_fu_27353_p2 + trunc_ln708_28_reg_28932);

assign add_ln703_92_fu_28766_p2 = (add_ln703_91_reg_29092 + add_ln703_89_fu_28760_p2);

assign add_ln703_93_fu_28771_p2 = ($signed(trunc_ln708_58_reg_29032) + $signed(sext_ln708_23_fu_28513_p1));

assign add_ln703_94_fu_27994_p2 = ($signed(trunc_ln708_88_fu_27732_p4) + $signed(sext_ln708_33_fu_27888_p1));

assign add_ln703_95_fu_28000_p2 = (add_ln703_94_fu_27994_p2 + trunc_ln708_78_reg_29174);

assign add_ln703_96_fu_28776_p2 = (add_ln703_95_reg_29234 + add_ln703_93_fu_28771_p2);

assign add_ln703_97_fu_28781_p2 = (add_ln703_96_fu_28776_p2 + add_ln703_92_fu_28766_p2);

assign add_ln703_9_fu_27257_p2 = (trunc_ln708_29_reg_28937 + trunc_ln708_39_fu_26992_p4);

assign add_ln703_fu_28517_p2 = ($signed(sext_ln708_2_fu_28201_p1) + $signed(trunc_ln_fu_28050_p4));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage1_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage2_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage3_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage4_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage1_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_return_0 = add_ln703_16_fu_28538_p2;

assign ap_return_1 = add_ln703_25_fu_28566_p2;

assign ap_return_2 = add_ln703_34_fu_28593_p2;

assign ap_return_3 = add_ln703_43_fu_28621_p2;

assign ap_return_4 = add_ln703_52_fu_28648_p2;

assign ap_return_5 = add_ln703_61_fu_28675_p2;

assign ap_return_6 = add_ln703_70_fu_28701_p2;

assign ap_return_7 = add_ln703_79_fu_28727_p2;

assign ap_return_8 = add_ln703_88_fu_28754_p2;

assign ap_return_9 = add_ln703_97_fu_28781_p2;

assign mul_ln1118_10_fu_440_p0 = sext_ln1118_7_fu_28179_p1;

assign mul_ln1118_10_fu_440_p1 = 26'd67108561;

assign mul_ln1118_11_fu_466_p0 = sext_ln1118_7_fu_28179_p1;

assign mul_ln1118_11_fu_466_p1 = 26'd386;

assign mul_ln1118_12_fu_390_p0 = sext_ln1118_8_fu_28186_p1;

assign mul_ln1118_12_fu_390_p1 = 25'd199;

assign mul_ln1118_13_fu_398_p0 = sext_ln1118_13_fu_26635_p1;

assign mul_ln1118_13_fu_398_p1 = 26'd67108489;

assign mul_ln1118_14_fu_467_p0 = sext_ln1118_13_fu_26635_p1;

assign mul_ln1118_14_fu_467_p1 = 26'd67108570;

assign mul_ln1118_15_fu_444_p0 = sext_ln1118_13_fu_26635_p1;

assign mul_ln1118_15_fu_444_p1 = 26'd67108358;

assign mul_ln1118_16_fu_445_p0 = sext_ln1118_13_fu_26635_p1;

assign mul_ln1118_16_fu_445_p1 = 26'd352;

assign mul_ln1118_17_fu_407_p0 = sext_ln1118_13_fu_26635_p1;

assign mul_ln1118_17_fu_407_p1 = 26'd394;

assign mul_ln1118_18_fu_420_p0 = sext_ln1118_13_fu_26635_p1;

assign mul_ln1118_18_fu_420_p1 = 26'd330;

assign mul_ln1118_19_fu_379_p0 = sext_ln1118_13_fu_26635_p1;

assign mul_ln1118_19_fu_379_p1 = 26'd67108491;

assign mul_ln1118_1_fu_385_p0 = sext_ln1118_fu_28005_p1;

assign mul_ln1118_1_fu_385_p1 = 26'd67108497;

assign mul_ln1118_20_fu_429_p0 = sext_ln1118_17_fu_26785_p1;

assign mul_ln1118_20_fu_429_p1 = 26'd67108546;

assign mul_ln1118_21_fu_442_p0 = sext_ln1118_16_fu_26778_p1;

assign mul_ln1118_21_fu_442_p1 = 23'd47;

assign mul_ln1118_22_fu_408_p0 = sext_ln1118_17_fu_26785_p1;

assign mul_ln1118_22_fu_408_p1 = 26'd67108475;

assign mul_ln1118_23_fu_389_p0 = sext_ln1118_17_fu_26785_p1;

assign mul_ln1118_23_fu_389_p1 = 26'd67108482;

assign mul_ln1118_24_fu_387_p0 = sext_ln1118_17_fu_26785_p1;

assign mul_ln1118_24_fu_387_p1 = 26'd300;

assign mul_ln1118_25_fu_382_p0 = sext_ln1118_16_fu_26778_p1;

assign mul_ln1118_25_fu_382_p1 = 23'd35;

assign mul_ln1118_26_fu_439_p0 = sext_ln1118_16_fu_26778_p1;

assign mul_ln1118_26_fu_439_p1 = 23'd8388573;

assign mul_ln1118_27_fu_409_p0 = sext_ln1118_17_fu_26785_p1;

assign mul_ln1118_27_fu_409_p1 = 26'd67108523;

assign mul_ln1118_28_fu_404_p0 = sext_ln1118_24_fu_26980_p1;

assign mul_ln1118_28_fu_404_p1 = 26'd67108527;

assign mul_ln1118_29_fu_423_p0 = sext_ln1118_24_fu_26980_p1;

assign mul_ln1118_29_fu_423_p1 = 26'd67108541;

assign mul_ln1118_2_fu_465_p1 = 25'd158;

assign mul_ln1118_30_fu_417_p0 = sext_ln1118_24_fu_26980_p1;

assign mul_ln1118_30_fu_417_p1 = 26'd431;

assign mul_ln1118_31_fu_406_p0 = sext_ln1118_24_fu_26980_p1;

assign mul_ln1118_31_fu_406_p1 = 26'd295;

assign mul_ln1118_32_fu_430_p0 = sext_ln1118_24_fu_26980_p1;

assign mul_ln1118_32_fu_430_p1 = 26'd67108355;

assign mul_ln1118_33_fu_374_p1 = 24'd16777113;

assign mul_ln1118_34_fu_433_p0 = sext_ln1118_24_fu_26980_p1;

assign mul_ln1118_34_fu_433_p1 = 26'd67108556;

assign mul_ln1118_35_fu_449_p0 = sext_ln1118_24_fu_26980_p1;

assign mul_ln1118_35_fu_449_p1 = 26'd67108560;

assign mul_ln1118_36_fu_435_p0 = sext_ln1118_24_fu_26980_p1;

assign mul_ln1118_36_fu_435_p1 = 26'd67108484;

assign mul_ln1118_37_fu_384_p1 = 23'd8388557;

assign mul_ln1118_38_fu_437_p0 = sext_ln1118_27_fu_27114_p1;

assign mul_ln1118_38_fu_437_p1 = 25'd33554256;

assign mul_ln1118_39_fu_411_p0 = sext_ln1118_27_fu_27114_p1;

assign mul_ln1118_39_fu_411_p1 = 25'd33554216;

assign mul_ln1118_3_fu_454_p0 = sext_ln1118_fu_28005_p1;

assign mul_ln1118_3_fu_454_p1 = 26'd458;

assign mul_ln1118_40_fu_381_p0 = sext_ln1118_27_fu_27114_p1;

assign mul_ln1118_40_fu_381_p1 = 25'd163;

assign mul_ln1118_41_fu_424_p0 = sext_ln1118_26_fu_27105_p1;

assign mul_ln1118_41_fu_424_p1 = 26'd67108380;

assign mul_ln1118_42_fu_378_p0 = sext_ln1118_26_fu_27105_p1;

assign mul_ln1118_42_fu_378_p1 = 26'd389;

assign mul_ln1118_43_fu_392_p0 = sext_ln1118_26_fu_27105_p1;

assign mul_ln1118_43_fu_392_p1 = 26'd67108559;

assign mul_ln1118_44_fu_448_p0 = sext_ln1118_26_fu_27105_p1;

assign mul_ln1118_44_fu_448_p1 = 26'd485;

assign mul_ln1118_45_fu_414_p1 = 23'd8388567;

assign mul_ln1118_46_fu_413_p0 = sext_ln1118_26_fu_27105_p1;

assign mul_ln1118_46_fu_413_p1 = 26'd436;

assign mul_ln1118_47_fu_434_p0 = sext_ln1118_31_fu_27369_p1;

assign mul_ln1118_47_fu_434_p1 = 26'd400;

assign mul_ln1118_48_fu_455_p0 = sext_ln1118_30_fu_27363_p1;

assign mul_ln1118_48_fu_455_p1 = 24'd83;

assign mul_ln1118_49_fu_456_p0 = sext_ln1118_31_fu_27369_p1;

assign mul_ln1118_49_fu_456_p1 = 26'd67108392;

assign mul_ln1118_4_fu_431_p0 = sext_ln1118_fu_28005_p1;

assign mul_ln1118_4_fu_431_p1 = 26'd300;

assign mul_ln1118_50_fu_396_p0 = sext_ln1118_30_fu_27363_p1;

assign mul_ln1118_50_fu_396_p1 = 24'd104;

assign mul_ln1118_51_fu_427_p0 = sext_ln1118_31_fu_27369_p1;

assign mul_ln1118_51_fu_427_p1 = 26'd393;

assign mul_ln1118_52_fu_468_p0 = sext_ln1118_31_fu_27369_p1;

assign mul_ln1118_52_fu_468_p1 = 26'd67108568;

assign mul_ln1118_53_fu_415_p0 = sext_ln1118_31_fu_27369_p1;

assign mul_ln1118_53_fu_415_p1 = 26'd466;

assign mul_ln1118_54_fu_395_p0 = sext_ln1118_39_fu_27453_p1;

assign mul_ln1118_54_fu_395_p1 = 26'd67108484;

assign mul_ln1118_55_fu_453_p0 = sext_ln1118_39_fu_27453_p1;

assign mul_ln1118_55_fu_453_p1 = 26'd67108389;

assign mul_ln1118_56_fu_418_p0 = sext_ln1118_39_fu_27453_p1;

assign mul_ln1118_56_fu_418_p1 = 26'd426;

assign mul_ln1118_57_fu_394_p0 = sext_ln1118_39_fu_27453_p1;

assign mul_ln1118_57_fu_394_p1 = 26'd67108586;

assign mul_ln1118_58_fu_388_p1 = 24'd103;

assign mul_ln1118_59_fu_412_p0 = sext_ln1118_39_fu_27453_p1;

assign mul_ln1118_59_fu_412_p1 = 26'd313;

assign mul_ln1118_5_fu_399_p0 = sext_ln1118_fu_28005_p1;

assign mul_ln1118_5_fu_399_p1 = 26'd67108591;

assign mul_ln1118_60_fu_443_p0 = sext_ln1118_39_fu_27453_p1;

assign mul_ln1118_60_fu_443_p1 = 26'd293;

assign mul_ln1118_61_fu_463_p0 = sext_ln1118_39_fu_27453_p1;

assign mul_ln1118_61_fu_463_p1 = 26'd311;

assign mul_ln1118_62_fu_436_p0 = sext_ln1118_45_fu_27625_p1;

assign mul_ln1118_62_fu_436_p1 = 26'd67108408;

assign mul_ln1118_63_fu_452_p0 = sext_ln1118_45_fu_27625_p1;

assign mul_ln1118_63_fu_452_p1 = 26'd308;

assign mul_ln1118_64_fu_416_p1 = 25'd33554186;

assign mul_ln1118_65_fu_403_p0 = sext_ln1118_45_fu_27625_p1;

assign mul_ln1118_65_fu_403_p1 = 26'd67108597;

assign mul_ln1118_66_fu_402_p0 = sext_ln1118_45_fu_27625_p1;

assign mul_ln1118_66_fu_402_p1 = 26'd447;

assign mul_ln1118_67_fu_405_p0 = sext_ln1118_45_fu_27625_p1;

assign mul_ln1118_67_fu_405_p1 = 26'd67108529;

assign mul_ln1118_68_fu_450_p0 = sext_ln1118_48_fu_27757_p1;

assign mul_ln1118_68_fu_450_p1 = 26'd359;

assign mul_ln1118_69_fu_377_p0 = sext_ln1118_48_fu_27757_p1;

assign mul_ln1118_69_fu_377_p1 = 26'd481;

assign mul_ln1118_6_fu_470_p0 = sext_ln1118_8_fu_28186_p1;

assign mul_ln1118_6_fu_470_p1 = 25'd33554179;

assign mul_ln1118_70_fu_457_p0 = sext_ln1118_47_fu_27751_p1;

assign mul_ln1118_70_fu_457_p1 = 23'd50;

assign mul_ln1118_71_fu_401_p0 = sext_ln1118_46_fu_27742_p1;

assign mul_ln1118_71_fu_401_p1 = 25'd138;

assign mul_ln1118_72_fu_451_p0 = sext_ln1118_46_fu_27742_p1;

assign mul_ln1118_72_fu_451_p1 = 25'd222;

assign mul_ln1118_73_fu_472_p0 = sext_ln1118_46_fu_27742_p1;

assign mul_ln1118_73_fu_472_p1 = 25'd33554200;

assign mul_ln1118_74_fu_428_p0 = sext_ln1118_48_fu_27757_p1;

assign mul_ln1118_74_fu_428_p1 = 26'd67108597;

assign mul_ln1118_75_fu_391_p0 = sext_ln1118_46_fu_27742_p1;

assign mul_ln1118_75_fu_391_p1 = 25'd33554301;

assign mul_ln1118_76_fu_410_p0 = sext_ln1118_47_fu_27751_p1;

assign mul_ln1118_76_fu_410_p1 = 23'd8388565;

assign mul_ln1118_77_fu_419_p0 = sext_ln1118_46_fu_27742_p1;

assign mul_ln1118_77_fu_419_p1 = 25'd33554289;

assign mul_ln1118_7_fu_380_p0 = sext_ln1118_7_fu_28179_p1;

assign mul_ln1118_7_fu_380_p1 = 26'd464;

assign mul_ln1118_8_fu_425_p0 = sext_ln1118_7_fu_28179_p1;

assign mul_ln1118_8_fu_425_p1 = 26'd499;

assign mul_ln1118_9_fu_422_p0 = sext_ln1118_6_fu_28175_p1;

assign mul_ln1118_9_fu_422_p1 = 24'd118;

assign mul_ln1118_fu_446_p0 = sext_ln1118_fu_28005_p1;

assign mul_ln1118_fu_446_p1 = 26'd392;

assign mul_ln708_1_fu_386_p0 = sext_ln1118_fu_28005_p1;

assign mul_ln708_1_fu_386_p1 = 26'd537;

assign mul_ln708_2_fu_471_p0 = sext_ln1118_13_fu_26635_p1;

assign mul_ln708_2_fu_471_p1 = 26'd560;

assign mul_ln708_3_fu_464_p0 = sext_ln1118_13_fu_26635_p1;

assign mul_ln708_3_fu_464_p1 = 26'd67108345;

assign mul_ln708_4_fu_447_p0 = sext_ln1118_45_fu_27625_p1;

assign mul_ln708_4_fu_447_p1 = 26'd67108332;

assign mul_ln708_5_fu_373_p0 = sext_ln1118_45_fu_27625_p1;

assign mul_ln708_5_fu_373_p1 = 26'd67108340;

assign mul_ln708_6_fu_469_p0 = sext_ln1118_45_fu_27625_p1;

assign mul_ln708_6_fu_469_p1 = 26'd523;

assign mul_ln708_7_fu_426_p0 = sext_ln1118_45_fu_27625_p1;

assign mul_ln708_7_fu_426_p1 = 26'd557;

assign mul_ln708_fu_375_p0 = sext_ln1118_fu_28005_p1;

assign mul_ln708_fu_375_p1 = 26'd546;

assign sext_ln1118_10_fu_28233_p1 = shl_ln1118_3_fu_28226_p3;

assign sext_ln1118_11_fu_28237_p1 = shl_ln1118_3_fu_28226_p3;

assign sext_ln1118_12_fu_28274_p1 = $signed(shl_ln1118_4_fu_28267_p3);

assign sext_ln1118_13_fu_26635_p0 = dense_input_q1;

assign sext_ln1118_13_fu_26635_p1 = sext_ln1118_13_fu_26635_p0;

assign sext_ln1118_14_fu_26726_p1 = $signed(shl_ln1118_5_fu_26718_p3);

assign sext_ln1118_15_fu_26738_p1 = $signed(shl_ln1118_6_fu_26730_p3);

assign sext_ln1118_16_fu_26778_p0 = dense_input_q0;

assign sext_ln1118_16_fu_26778_p1 = sext_ln1118_16_fu_26778_p0;

assign sext_ln1118_17_fu_26785_p0 = dense_input_q0;

assign sext_ln1118_17_fu_26785_p1 = sext_ln1118_17_fu_26785_p0;

assign sext_ln1118_18_fu_26885_p1 = $signed(shl_ln1118_7_fu_26877_p3);

assign sext_ln1118_19_fu_26897_p1 = $signed(shl_ln1118_8_fu_26889_p3);

assign sext_ln1118_1_fu_28015_p1 = dense_input_load_reg_28857;

assign sext_ln1118_20_fu_26932_p1 = $signed(shl_ln1118_9_fu_26924_p3);

assign sext_ln1118_21_fu_26944_p1 = $signed(shl_ln1118_10_fu_26936_p3);

assign sext_ln1118_24_fu_26980_p0 = dense_input_q1;

assign sext_ln1118_24_fu_26980_p1 = sext_ln1118_24_fu_26980_p0;

assign sext_ln1118_26_fu_27105_p0 = dense_input_q0;

assign sext_ln1118_26_fu_27105_p1 = sext_ln1118_26_fu_27105_p0;

assign sext_ln1118_27_fu_27114_p0 = dense_input_q0;

assign sext_ln1118_27_fu_27114_p1 = sext_ln1118_27_fu_27114_p0;

assign sext_ln1118_28_fu_27149_p1 = $signed(shl_ln1118_11_fu_27141_p3);

assign sext_ln1118_29_fu_27167_p1 = $signed(shl_ln1118_12_fu_27159_p3);

assign sext_ln1118_30_fu_27363_p0 = dense_input_q1;

assign sext_ln1118_30_fu_27363_p1 = sext_ln1118_30_fu_27363_p0;

assign sext_ln1118_31_fu_27369_p0 = dense_input_q1;

assign sext_ln1118_31_fu_27369_p1 = sext_ln1118_31_fu_27369_p0;

assign sext_ln1118_32_fu_28392_p1 = $signed(shl_ln1118_13_fu_28384_p3);

assign sext_ln1118_33_fu_28404_p1 = $signed(shl_ln1118_14_fu_28396_p3);

assign sext_ln1118_34_fu_28436_p1 = $signed(shl_ln1118_15_fu_28428_p3);

assign sext_ln1118_35_fu_28454_p1 = shl_ln1118_16_fu_28446_p3;

assign sext_ln1118_36_fu_28458_p1 = shl_ln1118_16_fu_28446_p3;

assign sext_ln1118_37_fu_28493_p1 = $signed(shl_ln1118_17_fu_28485_p3);

assign sext_ln1118_39_fu_27453_p0 = dense_input_q0;

assign sext_ln1118_39_fu_27453_p1 = sext_ln1118_39_fu_27453_p0;

assign sext_ln1118_3_fu_28029_p1 = $signed(shl_ln_fu_28022_p3);

assign sext_ln1118_40_fu_27551_p1 = $signed(shl_ln1118_18_fu_27544_p3);

assign sext_ln1118_41_fu_27562_p1 = shl_ln1118_19_fu_27555_p3;

assign sext_ln1118_42_fu_27566_p1 = shl_ln1118_19_fu_27555_p3;

assign sext_ln1118_43_fu_27600_p1 = $signed(shl_ln1118_20_fu_27593_p3);

assign sext_ln1118_45_fu_27625_p0 = dense_input_q1;

assign sext_ln1118_45_fu_27625_p1 = sext_ln1118_45_fu_27625_p0;

assign sext_ln1118_46_fu_27742_p0 = dense_input_q0;

assign sext_ln1118_46_fu_27742_p1 = sext_ln1118_46_fu_27742_p0;

assign sext_ln1118_47_fu_27751_p0 = dense_input_q0;

assign sext_ln1118_47_fu_27751_p1 = sext_ln1118_47_fu_27751_p0;

assign sext_ln1118_48_fu_27757_p0 = dense_input_q0;

assign sext_ln1118_48_fu_27757_p1 = sext_ln1118_48_fu_27757_p0;

assign sext_ln1118_4_fu_28040_p1 = $signed(shl_ln1118_s_fu_28033_p3);

assign sext_ln1118_5_fu_28067_p1 = $signed(shl_ln1118_1_fu_28060_p3);

assign sext_ln1118_6_fu_28175_p1 = dense_input_load_1_reg_28867;

assign sext_ln1118_7_fu_28179_p1 = dense_input_load_1_reg_28867;

assign sext_ln1118_8_fu_28186_p1 = dense_input_load_1_reg_28867;

assign sext_ln1118_9_fu_28222_p1 = $signed(shl_ln1118_2_fu_28215_p3);

assign sext_ln1118_fu_28005_p1 = dense_input_load_reg_28857;

assign sext_ln708_10_fu_26964_p1 = $signed(trunc_ln708_36_reg_28962);

assign sext_ln708_11_fu_26967_p1 = $signed(trunc_ln708_37_reg_28967);

assign sext_ln708_12_fu_27052_p1 = $signed(trunc_ln708_44_fu_27042_p4);

assign sext_ln708_13_fu_27096_p1 = $signed(trunc_ln708_48_fu_27086_p4);

assign sext_ln708_14_fu_28366_p1 = $signed(trunc_ln708_49_reg_28987);

assign sext_ln708_15_fu_28369_p1 = $signed(trunc_ln708_50_reg_28992);

assign sext_ln708_16_fu_28372_p1 = $signed(trunc_ln708_51_reg_28997);

assign sext_ln708_17_fu_28375_p1 = $signed(trunc_ln708_52_reg_29002);

assign sext_ln708_18_fu_28378_p1 = $signed(trunc_ln708_57_reg_29027);

assign sext_ln708_19_fu_28381_p1 = $signed(trunc_ln708_60_reg_29102);

assign sext_ln708_1_fu_28131_p1 = $signed(trunc_ln708_5_fu_28121_p4);

assign sext_ln708_20_fu_28424_p1 = $signed(trunc_ln708_62_fu_28414_p4);

assign sext_ln708_21_fu_28478_p1 = $signed(trunc_ln708_63_fu_28468_p4);

assign sext_ln708_22_fu_28482_p1 = $signed(trunc_ln708_64_reg_29112);

assign sext_ln708_23_fu_28513_p1 = $signed(trunc_ln708_68_fu_28503_p4);

assign sext_ln708_24_fu_27586_p1 = $signed(trunc_ln708_69_fu_27576_p4);

assign sext_ln708_25_fu_27590_p1 = $signed(trunc_ln708_74_reg_29159);

assign sext_ln708_26_fu_27708_p1 = $signed(trunc_ln708_85_fu_27698_p4);

assign sext_ln708_27_fu_27794_p1 = $signed(trunc_ln708_91_fu_27784_p4);

assign sext_ln708_28_fu_27808_p1 = $signed(trunc_ln708_92_fu_27798_p4);

assign sext_ln708_29_fu_27822_p1 = $signed(trunc_ln708_93_fu_27812_p4);

assign sext_ln708_2_fu_28201_p1 = $signed(trunc_ln708_s_fu_28191_p4);

assign sext_ln708_30_fu_27836_p1 = $signed(trunc_ln708_94_fu_27826_p4);

assign sext_ln708_31_fu_27860_p1 = $signed(trunc_ln708_96_fu_27850_p4);

assign sext_ln708_32_fu_27874_p1 = $signed(trunc_ln708_97_fu_27864_p4);

assign sext_ln708_33_fu_27888_p1 = $signed(trunc_ln708_98_fu_27878_p4);

assign sext_ln708_3_fu_28294_p1 = $signed(trunc_ln708_13_fu_28284_p4);

assign sext_ln708_4_fu_28308_p1 = $signed(trunc_ln708_14_fu_28298_p4);

assign sext_ln708_5_fu_28348_p1 = $signed(trunc_ln708_17_fu_28338_p4);

assign sext_ln708_6_fu_28362_p1 = $signed(trunc_ln708_18_fu_28352_p4);

assign sext_ln708_7_fu_26874_p1 = $signed(trunc_ln708_26_reg_28922);

assign sext_ln708_8_fu_26917_p1 = $signed(trunc_ln708_30_fu_26907_p4);

assign sext_ln708_9_fu_26921_p1 = $signed(trunc_ln708_31_reg_28942);

assign sext_ln708_fu_28087_p1 = $signed(trunc_ln708_1_fu_28077_p4);

assign shl_ln1118_10_fu_26936_p3 = {{reg_26630}, {3'd0}};

assign shl_ln1118_11_fu_27141_p1 = dense_input_q0;

assign shl_ln1118_11_fu_27141_p3 = {{shl_ln1118_11_fu_27141_p1}, {4'd0}};

assign shl_ln1118_12_fu_27159_p1 = dense_input_q0;

assign shl_ln1118_12_fu_27159_p3 = {{shl_ln1118_12_fu_27159_p1}, {2'd0}};

assign shl_ln1118_13_fu_28384_p3 = {{reg_26630}, {8'd0}};

assign shl_ln1118_14_fu_28396_p3 = {{reg_26630}, {5'd0}};

assign shl_ln1118_15_fu_28428_p3 = {{reg_26630}, {4'd0}};

assign shl_ln1118_16_fu_28446_p3 = {{reg_26630}, {1'd0}};

assign shl_ln1118_17_fu_28485_p3 = {{reg_26630}, {6'd0}};

assign shl_ln1118_18_fu_27544_p3 = {{dense_input_load_7_reg_29132}, {4'd0}};

assign shl_ln1118_19_fu_27555_p3 = {{dense_input_load_7_reg_29132}, {2'd0}};

assign shl_ln1118_1_fu_28060_p3 = {{dense_input_load_reg_28857}, {3'd0}};

assign shl_ln1118_20_fu_27593_p3 = {{dense_input_load_7_reg_29132}, {9'd0}};

assign shl_ln1118_2_fu_28215_p3 = {{dense_input_load_1_reg_28867}, {9'd0}};

assign shl_ln1118_3_fu_28226_p3 = {{dense_input_load_1_reg_28867}, {1'd0}};

assign shl_ln1118_4_fu_28267_p3 = {{dense_input_load_1_reg_28867}, {7'd0}};

assign shl_ln1118_5_fu_26718_p1 = dense_input_q1;

assign shl_ln1118_5_fu_26718_p3 = {{shl_ln1118_5_fu_26718_p1}, {8'd0}};

assign shl_ln1118_6_fu_26730_p1 = dense_input_q1;

assign shl_ln1118_6_fu_26730_p3 = {{shl_ln1118_6_fu_26730_p1}, {6'd0}};

assign shl_ln1118_7_fu_26877_p3 = {{reg_26630}, {7'd0}};

assign shl_ln1118_8_fu_26889_p3 = {{reg_26630}, {2'd0}};

assign shl_ln1118_9_fu_26924_p3 = {{reg_26630}, {9'd0}};

assign shl_ln1118_s_fu_28033_p3 = {{dense_input_load_reg_28857}, {5'd0}};

assign shl_ln_fu_28022_p3 = {{dense_input_load_reg_28857}, {9'd0}};

assign sub_ln1118_10_fu_27570_p2 = ($signed(sext_ln1118_42_fu_27566_p1) - $signed(sext_ln1118_40_fu_27551_p1));

assign sub_ln1118_11_fu_27604_p2 = ($signed(sext_ln1118_43_fu_27600_p1) - $signed(sext_ln1118_41_fu_27562_p1));

assign sub_ln1118_12_fu_28332_p2 = ($signed(sext_ln1118_6_fu_28175_p1) - $signed(sext_ln1118_12_fu_28274_p1));

assign sub_ln1118_1_fu_28241_p2 = ($signed(sext_ln1118_11_fu_28237_p1) - $signed(sext_ln1118_9_fu_28222_p1));

assign sub_ln1118_2_fu_26901_p2 = ($signed(sext_ln1118_18_fu_26885_p1) - $signed(sext_ln1118_19_fu_26897_p1));

assign sub_ln1118_3_fu_26948_p2 = ($signed(sext_ln1118_20_fu_26932_p1) - $signed(sext_ln1118_21_fu_26944_p1));

assign sub_ln1118_4_fu_27153_p2 = ($signed(21'd0) - $signed(sext_ln1118_28_fu_27149_p1));

assign sub_ln1118_5_fu_27171_p2 = ($signed(sub_ln1118_4_fu_27153_p2) - $signed(sext_ln1118_29_fu_27167_p1));

assign sub_ln1118_6_fu_28408_p2 = ($signed(sext_ln1118_32_fu_28392_p1) - $signed(sext_ln1118_33_fu_28404_p1));

assign sub_ln1118_7_fu_28440_p2 = ($signed(21'd0) - $signed(sext_ln1118_34_fu_28436_p1));

assign sub_ln1118_8_fu_28462_p2 = ($signed(sub_ln1118_7_fu_28440_p2) - $signed(sext_ln1118_36_fu_28458_p1));

assign sub_ln1118_9_fu_28497_p2 = ($signed(sext_ln1118_37_fu_28493_p1) - $signed(sext_ln1118_35_fu_28454_p1));

assign sub_ln1118_fu_28071_p2 = ($signed(sext_ln1118_5_fu_28067_p1) - $signed(sext_ln1118_1_fu_28015_p1));

assign trunc_ln708_10_fu_28205_p4 = {{mul_ln1118_7_fu_380_p2[25:10]}};

assign trunc_ln708_11_fu_28247_p4 = {{sub_ln1118_1_fu_28241_p2[25:10]}};

assign trunc_ln708_12_fu_28257_p4 = {{mul_ln1118_8_fu_425_p2[25:10]}};

assign trunc_ln708_13_fu_28284_p4 = {{add_ln1118_1_fu_28278_p2[23:10]}};

assign trunc_ln708_14_fu_28298_p4 = {{mul_ln1118_9_fu_422_p2[23:10]}};

assign trunc_ln708_15_fu_28312_p4 = {{mul_ln1118_10_fu_440_p2[25:10]}};

assign trunc_ln708_16_fu_28322_p4 = {{mul_ln1118_11_fu_466_p2[25:10]}};

assign trunc_ln708_17_fu_28338_p4 = {{sub_ln1118_12_fu_28332_p2[23:10]}};

assign trunc_ln708_18_fu_28352_p4 = {{mul_ln1118_12_fu_390_p2[24:10]}};

assign trunc_ln708_1_fu_28077_p4 = {{sub_ln1118_fu_28071_p2[19:10]}};

assign trunc_ln708_2_fu_28091_p4 = {{mul_ln1118_fu_446_p2[25:10]}};

assign trunc_ln708_30_fu_26907_p4 = {{sub_ln1118_2_fu_26901_p2[23:10]}};

assign trunc_ln708_34_fu_26954_p4 = {{sub_ln1118_3_fu_26948_p2[25:10]}};

assign trunc_ln708_39_fu_26992_p4 = {{mul_ln1118_28_fu_404_p2[25:10]}};

assign trunc_ln708_3_fu_28101_p4 = {{mul_ln1118_1_fu_385_p2[25:10]}};

assign trunc_ln708_40_fu_27002_p4 = {{mul_ln1118_29_fu_423_p2[25:10]}};

assign trunc_ln708_41_fu_27012_p4 = {{mul_ln1118_30_fu_417_p2[25:10]}};

assign trunc_ln708_42_fu_27022_p4 = {{mul_ln1118_31_fu_406_p2[25:10]}};

assign trunc_ln708_43_fu_27032_p4 = {{mul_ln1118_32_fu_430_p2[25:10]}};

assign trunc_ln708_44_fu_27042_p4 = {{mul_ln1118_33_fu_374_p2[23:10]}};

assign trunc_ln708_45_fu_27056_p4 = {{mul_ln1118_34_fu_433_p2[25:10]}};

assign trunc_ln708_46_fu_27066_p4 = {{mul_ln1118_35_fu_449_p2[25:10]}};

assign trunc_ln708_47_fu_27076_p4 = {{mul_ln1118_36_fu_435_p2[25:10]}};

assign trunc_ln708_48_fu_27086_p4 = {{mul_ln1118_37_fu_384_p2[22:10]}};

assign trunc_ln708_4_fu_28111_p4 = {{mul_ln708_fu_375_p2[25:10]}};

assign trunc_ln708_5_fu_28121_p4 = {{mul_ln1118_2_fu_465_p2[24:10]}};

assign trunc_ln708_62_fu_28414_p4 = {{sub_ln1118_6_fu_28408_p2[24:10]}};

assign trunc_ln708_63_fu_28468_p4 = {{sub_ln1118_8_fu_28462_p2[20:10]}};

assign trunc_ln708_68_fu_28503_p4 = {{sub_ln1118_9_fu_28497_p2[22:10]}};

assign trunc_ln708_69_fu_27576_p4 = {{sub_ln1118_10_fu_27570_p2[20:10]}};

assign trunc_ln708_6_fu_28135_p4 = {{mul_ln1118_3_fu_454_p2[25:10]}};

assign trunc_ln708_75_fu_27610_p4 = {{sub_ln1118_11_fu_27604_p2[25:10]}};

assign trunc_ln708_79_fu_27638_p4 = {{mul_ln708_4_fu_447_p2[25:10]}};

assign trunc_ln708_7_fu_28145_p4 = {{mul_ln1118_4_fu_431_p2[25:10]}};

assign trunc_ln708_80_fu_27648_p4 = {{mul_ln708_5_fu_373_p2[25:10]}};

assign trunc_ln708_81_fu_27658_p4 = {{mul_ln708_6_fu_469_p2[25:10]}};

assign trunc_ln708_82_fu_27668_p4 = {{mul_ln1118_62_fu_436_p2[25:10]}};

assign trunc_ln708_83_fu_27678_p4 = {{mul_ln1118_63_fu_452_p2[25:10]}};

assign trunc_ln708_84_fu_27688_p4 = {{mul_ln708_7_fu_426_p2[25:10]}};

assign trunc_ln708_85_fu_27698_p4 = {{mul_ln1118_64_fu_416_p2[24:10]}};

assign trunc_ln708_86_fu_27712_p4 = {{mul_ln1118_65_fu_403_p2[25:10]}};

assign trunc_ln708_87_fu_27722_p4 = {{mul_ln1118_66_fu_402_p2[25:10]}};

assign trunc_ln708_88_fu_27732_p4 = {{mul_ln1118_67_fu_405_p2[25:10]}};

assign trunc_ln708_89_fu_27764_p4 = {{mul_ln1118_68_fu_450_p2[25:10]}};

assign trunc_ln708_8_fu_28155_p4 = {{mul_ln1118_5_fu_399_p2[25:10]}};

assign trunc_ln708_90_fu_27774_p4 = {{mul_ln1118_69_fu_377_p2[25:10]}};

assign trunc_ln708_91_fu_27784_p4 = {{mul_ln1118_70_fu_457_p2[22:10]}};

assign trunc_ln708_92_fu_27798_p4 = {{mul_ln1118_71_fu_401_p2[24:10]}};

assign trunc_ln708_93_fu_27812_p4 = {{mul_ln1118_72_fu_451_p2[24:10]}};

assign trunc_ln708_94_fu_27826_p4 = {{mul_ln1118_73_fu_472_p2[24:10]}};

assign trunc_ln708_95_fu_27840_p4 = {{mul_ln1118_74_fu_428_p2[25:10]}};

assign trunc_ln708_96_fu_27850_p4 = {{mul_ln1118_75_fu_391_p2[24:10]}};

assign trunc_ln708_97_fu_27864_p4 = {{mul_ln1118_76_fu_410_p2[22:10]}};

assign trunc_ln708_98_fu_27878_p4 = {{mul_ln1118_77_fu_419_p2[24:10]}};

assign trunc_ln708_9_fu_28165_p4 = {{mul_ln708_1_fu_386_p2[25:10]}};

assign trunc_ln708_s_fu_28191_p4 = {{mul_ln1118_6_fu_470_p2[24:10]}};

assign trunc_ln_fu_28050_p4 = {{add_ln1118_fu_28044_p2[25:10]}};

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_16_6_5_3_0_config2_s
