// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2020.2 (64-bit)
// Version: 2020.2
// Copyright (C) Copyright 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config2_s (
        ap_ready,
        p_read,
        ap_return_0,
        ap_return_1
);


output   ap_ready;
input  [15:0] p_read;
output  [32:0] ap_return_0;
output  [32:0] ap_return_1;

wire  signed [15:0] mul_ln1118_fu_30_p0;
wire  signed [26:0] sext_ln70_fu_63_p1;
wire  signed [10:0] mul_ln1118_fu_30_p1;
wire  signed [15:0] mul_ln1118_1_fu_31_p0;
wire   [10:0] mul_ln1118_1_fu_31_p1;
wire   [26:0] mul_ln1118_fu_30_p2;
wire   [26:0] mul_ln1118_1_fu_31_p2;
wire  signed [32:0] sext_ln703_fu_69_p1;
wire  signed [32:0] sext_ln703_1_fu_73_p1;

myproject_mul_16s_11s_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11s_27_1_1_U1(
    .din0(mul_ln1118_fu_30_p0),
    .din1(mul_ln1118_fu_30_p1),
    .dout(mul_ln1118_fu_30_p2)
);

myproject_mul_16s_11ns_27_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 16 ),
    .din1_WIDTH( 11 ),
    .dout_WIDTH( 27 ))
mul_16s_11ns_27_1_1_U2(
    .din0(mul_ln1118_1_fu_31_p0),
    .din1(mul_ln1118_1_fu_31_p1),
    .dout(mul_ln1118_1_fu_31_p2)
);

assign ap_ready = 1'b1;

assign ap_return_0 = sext_ln703_fu_69_p1;

assign ap_return_1 = sext_ln703_1_fu_73_p1;

assign mul_ln1118_1_fu_31_p0 = sext_ln70_fu_63_p1;

assign mul_ln1118_1_fu_31_p1 = 27'd779;

assign mul_ln1118_fu_30_p0 = sext_ln70_fu_63_p1;

assign mul_ln1118_fu_30_p1 = 27'd134216792;

assign sext_ln703_1_fu_73_p1 = $signed(mul_ln1118_1_fu_31_p2);

assign sext_ln703_fu_69_p1 = $signed(mul_ln1118_fu_30_p2);

assign sext_ln70_fu_63_p1 = $signed(p_read);

endmodule //myproject_dense_latency_ap_fixed_16_6_5_3_0_ap_fixed_33_13_5_3_0_config2_s
